require('dotenv').config();
const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const REWRITES = [
  {
    // 2dccb4df - was 5, "severity classification is too generic without platform, cert, player impact, or business constraints"
    prefix: '2dccb4df',
    text: `You are QA lead on a free-to-play PvP shooter targeting PS5, Xbox Series X, and PC via Steam. The release candidate build has 40 open bugs and engineering can fix 12 before the Tuesday cert submission window. The 40 include: four crashes -- two on PS5 during map transitions (one reproduces 100% when loading the desert map after a ranked match, one is intermittent at roughly 1-in-20 map loads), one on Xbox when accepting a party invite from the system dashboard during the end-of-match XP screen, and one on PC tied to alt-tabbing while the anti-cheat kernel driver initialises on first launch only. Six gameplay bugs: a wall-breach exploit on one competitive map that has been posted on Reddit with 2,000 upvotes and a reproduction video, a UI overlap that hides the real-money purchase confirmation button on ultrawide monitors at 21:9 and 32:9 (monetisation team estimates 8% of PC players use ultrawide), an audio desync on all platforms when more than 8 players use abilities simultaneously in the same zone, a weapon dealing 0 damage on headshots when the target is on a ladder, an incorrect hitbox on one character's crouch animation that makes headshots register as body shots, and a memory leak in the spectator camera that reaches 800MB after 40 minutes. The remaining 30 range from cosmetic texture seams to minor localisation truncation in German and Japanese UI strings. Sony TRC requires zero crash-to-dashboard in normal play flows; Microsoft XR has equivalent requirements; Steam has no formal cert but the wall exploit will generate refund requests within hours of launch. The monetisation team says the store UI bug on ultrawide could trigger Apple/Google-style refund cascade precedent on PC storefronts. You have 12 engineering slots. Classify all 40 into severity tiers with your reasoning for each tier, select your 12, justify every inclusion and exclusion, and write the risk acceptance brief for the 28 bugs that ship -- including which ones need a day-one patch commitment to the platform holders.`
  },
  {
    // 70651779 - was 6, "'who you disappoint' pulls toward temperament unless tied to explicit release-risk criteria"
    prefix: '70651779',
    text: `You are the sole QA tester on a 4v4 co-op extraction shooter targeting PS5, Xbox, and PC. It is Tuesday 2pm and you have 14 working hours before Wednesday's end of day. Three competing requests: (1) The engineering lead needs regression testing on a host-migration patch deploying Wednesday morning. The previous host-migration patch caused a 15% disconnect spike that triggered a Sony compliance warning letter -- one more incident and Sony will require a full re-certification of the networking stack. The patch changes how player state is serialised during migration, touching 14 files across the session management, inventory persistence, and matchmaking modules. You need to test: host leaving during extraction countdown, host disconnecting during loot distribution, host migration when the migrating host has a different NAT type, and migration during the anti-cheat heartbeat window. (2) The art director needs animation verification across all 12 heroes for a publisher milestone demo Thursday at 10am. The publisher flagged animation quality as a greenlight risk last milestone. Two heroes have new ability animations -- a grapple hook and a shield bash -- that have never been tested on console builds, only PC. The grapple hook's rope physics are tied to frame rate and the PS5 build runs at variable 40-60fps in the relevant environments. (3) Three blocker bugs: a crash (100% repro) when a full 4-player squad enters extraction zone C on the refinery map, a progression-wipe that fires when a player levels up during a loading screen between zones (reported by 3 players in the community beta, repro steps unclear), and a matchmaking failure when cross-play parties include both PS5 and Xbox players with strict NAT. Lay out your hour-by-hour plan across 14 hours, specify what you cut and what risk each cut carries, and for each deprioritised item, state the concrete production consequence if the risk materialises.`
  },
  {
    // ee4e6b34 - was 6, "needs sharper player-impact and severity details"
    prefix: 'ee4e6b34',
    text: `You are QA on a live-service competitive FPS with 80,000 concurrent players at peak. A hotfix is on staging at 9:15pm Friday to fix a matchmaking bug placing Diamond-ranked players (SR 3000-3500) into Bronze lobbies (SR 0-500). The community manager reports 400+ Discord complaints in the past hour, two streamers are broadcasting broken matchmaking to 50,000 combined viewers, and the game's subreddit has a pinned thread with 1,200 upvotes titled "matchmaking completely broken." The live ops engineer's fix modifies the MMR query to re-add a rank-band filter accidentally removed in the afternoon's content patch -- specifically, a WHERE clause was dropped when a new seasonal playlist was added and the query was refactored. During your staging verification you confirm rank-band filtering works: 200 test matches across Bronze, Silver, Gold, and Diamond all placed within correct SR ranges. But you discover a second bug: the daily challenge tracker is not incrementing kill counts for any weapon except the default rifle (ID: weapon_ar_01). This affects 14 of the 18 daily challenges currently active, the weekly challenge set (3 of 5 require specific weapons), and the battle pass which has a timed seasonal event ending Sunday at midnight UTC -- players who cannot complete weapon-specific challenges will miss limited-time cosmetic rewards that cannot be obtained after the event. Approximately 60% of the active player base engages with challenges daily based on telemetry. The challenge bug exists in the progression microservice; the matchmaking fix is in the matchmaking microservice. They share no code paths and the challenge bug was present before the hotfix. The producer calls you at 9:45pm asking for a go/no-go on pushing the matchmaking hotfix to production right now. What is your recommendation, what specific information do you communicate, and what is your plan for the challenge bug given the 53-hour window before the event expires?`
  },
  {
    // 48781dad - was 6, "sprint-review status framing not specific enough to prove shipped-game QA competence"
    prefix: '48781dad',
    text: `You are QA lead on a 40-person studio's multiplayer title, four months from console cert submission. The production director gives you 5 minutes at the weekly all-hands sprint review. Your data from last sprint: 340 test cases executed across PS5, Xbox, and PC; 28 new bugs filed (3 critical -- a desync during ability casting that affects ranked play, a memory leak in the UI system that crashes after 90 minutes on PS5, and a cert-blocking issue where the game does not handle controller disconnect during save); 19 bug fixes verified and closed; 7 bugs reopened because the fixes introduced regressions; automated regression suite runtime increased from 4 hours to 6.5 hours due to new seasonal content test cases and 3 flaky tests that need investigation. You also identified a systemic issue: the anti-cheat system kicks legitimate players on Wi-Fi connections with packet loss above 2%, which affects an estimated 12% of the console player base based on telemetry from the open beta. The engineering lead disputes the 12% figure and says the anti-cheat vendor's documentation specifies a 5% packet loss threshold, not 2%. Your testing shows disconnections starting at 2.1% packet loss using the network simulation tools on devkits, and you have packet captures from 8 test sessions proving it. The audience includes 6 engineers, 5 artists, 4 designers, 2 producers, the studio head, and the publishing producer (remote). What do you present in those 5 minutes, in what order, what data visualisation do you use for the anti-cheat issue to make the engineering dispute resolvable rather than argumentative, and what do you explicitly leave out to stay within time?`
  },
  {
    // 3fbaa260 - was 5, "lacks platform, logs, build context, or a forced diagnostic path"
    prefix: '3fbaa260',
    text: `You are QA on an open-world action RPG targeting PS5 and Xbox Series X. The daily build crashes intermittently: the overnight soak test hit a crash at 47 minutes, a second run crashed at 40 minutes, but a third ran 2 hours clean. The crash dump shows an access violation in the streaming system (0xC0000005 at WorldStreaming::LoadChunk), but the callstack varies between runs -- one trace shows the fault in terrain LOD streaming, another in NPC spawn streaming, and the third clean run's memory profile shows streaming pool usage peaking at 94% before stabilising. The build includes 14 merged PRs: three terrain streaming PRs (one refactors the chunk loading priority queue), four NPC AI pathing PRs, three weather system PRs (one adds a new rain particle system that allocates from the streaming pool), and four weapon VFX PRs. The engine's streaming debugger shows the terrain PR changed the chunk eviction policy from LRU to priority-based, and the weather PR added a new allocation category to the streaming pool that does not appear in the pool budget spreadsheet. You have: the previous stable build (no terrain or weather changes), crash dumps from both failures, the engine's memory profiler and streaming debugger, GPU capture tools, the full PR list with diffs, and access to the CI build system that can produce a build from any commit combination. The publisher's review playthrough is tomorrow at 2pm. Walk through your diagnostic process: how you determine whether this is a memory leak (growing allocation), a race condition (timing-dependent), or a content-triggered fault (specific world location), what bisection strategy you use with the CI system to isolate the offending PR, and what you hand engineering by end of day if you cannot get a clean reproduction.`
  },
  {
    // 4a703552 - was 5, "asks for broad knowledge rather than scenario-specific test judgement"
    prefix: '4a703552',
    text: `Your studio is submitting a third-person action game simultaneously to PlayStation (PS5) and Xbox (Series X|S) in three weeks. The game has a 15-hour campaign, online leaderboards, and 4-player co-op. During your last milestone you hit: PS5 cold boot to main menu takes 58 seconds (Sony guideline: under 60 seconds, but your loading screen implementation does not show interactive UI for the first 40 seconds -- Sony's TRC 4.4 requires user-interactive content within 30 seconds of launch or the loading screen must display a progress indicator, which yours does not); Xbox suspend/resume drops the co-op connection without an error message (XR 074 requires the game to handle suspend gracefully and inform the user of connectivity changes); controller disconnect during save corrupts the save file 1-in-5 times because the save system uses a synchronous write that blocks the input polling thread, and when the controller reconnects the input thread reinitialises and interrupts the write. You have 2 QA testers total, 1 PS5 devkit, and 2 Xbox devkits. A cert failure costs 4 weeks of resubmission plus engineering time. You also know from industry contacts that Sony has been particularly strict on TRC 4.4 this quarter and has rejected two other titles for the same interactive-content-during-load requirement. Build your three-week test plan: prioritise cert-risk areas with specific TRC/XR requirement numbers, allocate the two testers across hardware accounting for devkit availability, specify which cert areas you test exhaustively versus sample, and identify the point at which you recommend the studio delay submission rather than risk a fail.`
  },
  {
    // 58bef60b - was 6, "needs details on features, platforms, fix areas, or cert-risk surface"
    prefix: '58bef60b',
    text: `Your studio is submitting a patch for a live multiplayer arena brawler on PS5, Xbox, and PC. The patch contains 30 bug fixes and 2 new features: a new character (melee assassin with dash, backstab, smoke bomb, and an ultimate that makes them invisible for 6 seconds with a shimmer VFX visible within 3 metres) and a clan system (create/join/leave, clan chat, invite by player ID, shared resource pool where members contribute soft currency and the clan leader allocates it to clan-wide buffs). Of the 30 fixes: 8 touch the networking layer (including one that changes how the server reconciles position during the new character's dash -- previously the server trusted the client position during dashes, now it does server-side pathfinding validation), 5 are PS5 suspend/resume fixes (including one that changes how the auth token refresh works after resume), 10 are balance adjustments (damage values, cooldown timers), and 7 are UI fixes (text truncation, tooltip positioning). Your team is you plus one junior tester who has never tested cert. You have 2 PS5 devkits, 2 Xbox devkits, 2 PC test machines, and a staging server that supports 8 simultaneous players maximum. The cert submission window closes at 6pm tomorrow -- you have roughly 9 working hours. Walk through your triage: what you test first and why (map the 30 fixes to risk categories), what you assign to the junior tester with specific instructions, what you skip with written risk documentation per skipped area, and your decision process if at 3pm you find a new desync bug caused by the dash reconciliation fix that only manifests when the assassin dashes through a smoke bomb while being hit by a melee attack.`
  },
  {
    // 7020f1ce - was 6, "too broad unless it names transaction flow, platform, server authority, or logging constraints"
    prefix: '7020f1ce',
    text: `You are QA on a free-to-play mobile RPG with server-authoritative economy. A community-posted video shows a currency duplication exploit: a player opens the in-game store, purchases a 500-gem crafting bundle (gems are the premium currency, purchased with real money at USD 0.99 per 100 gems), then force-closes the app during the "Transaction Processing" animation that plays for 2-3 seconds between the purchase request and the confirmation screen. On reconnection, the player has both the crafting bundle items in their inventory and the 500 gems back in their balance. The video shows it working on iOS with an iPhone 14 on iOS 17.2. The game's transaction architecture: the client sends a purchase request to the API gateway, which routes to the currency service (deducts gems and returns a transaction ID) and then to the inventory service (grants items using the transaction ID). The currency service and inventory service use eventual consistency with a message queue -- the currency service publishes a "deduction confirmed" event, and the inventory service consumes it. If the inventory service does not acknowledge within 30 seconds, the currency service's compensation handler refunds the gems. The force-close interrupts the client's acknowledgement of the inventory grant, and the server's compensation handler interprets the missing acknowledgement as a failed transaction. You have: the staging environment, server transaction logs (currency service and inventory service, separate databases), the client network traffic logger, iOS and Android test devices (iOS 17.2, iOS 16.4, Android 14, Android 12), a test account with 10,000 admin-granted gems, and a network proxy tool that can simulate app-kill timing. Reproduce the exploit, verify the exact failure window, test whether Android's different app lifecycle (which sends onPause before process kill, unlike iOS's immediate SIGKILL) is also vulnerable, and design regression scenarios for the fix that cover legitimate network drops mid-transaction, backgrounding without force-close, and multi-device login during a pending transaction.`
  },
  {
    // 8ab81ad4 - was 6, "'beyond basic connectivity' is open-ended and allows rehearsed checklist answers"
    prefix: '8ab81ad4',
    text: `You are QA on a 6v6 hero shooter launching on PC, PS5, and Xbox with full cross-play. Connectivity and matchmaking are verified. You need to test four specific cross-play subsystems that interact in non-obvious ways. (1) Input fairness: PC players have aim assist disabled; console players have aim assist curves that differ between PS5 (DualSense gyro aim available) and Xbox (no gyro). The game has a ranked mode toggle: "Input-Based Matchmaking" that pools by input device, not platform -- so a PS5 player using a keyboard should match with PC players, and a PC player using a controller should get aim assist and match with console players. A PS5 player can hot-swap from controller to keyboard mid-match. (2) Voice and text chat: cross-platform parties use the game's built-in VOIP (Vivox SDK), but same-platform parties can use PlayStation Party Chat or Xbox Party Chat which operate outside the game. If two PS5 players are in Party Chat and one joins a cross-play squad, the other three squad members cannot hear them. Text chat has three different profanity filters -- Sony's, Microsoft's, and the game's custom filter for PC. Sony's filter blocks "kill" in certain contexts; Microsoft's does not. A message sent by a PC player may appear differently to PS5 and Xbox recipients. (3) Block/report: blocking a player on PSN should prevent matching with them on any platform, but the game's internal block list and PSN's block list are separate systems. If Player A blocks Player B on PSN but not in-game, does matchmaking respect it? (4) Party invites: the game supports platform friend lists and an in-game friend code. Inviting an Xbox player to a PS5 player's party via friend code while the Xbox player has cross-play disabled in their Xbox system settings (not the game settings) should show an error, but the error path has never been tested. You have 2 PS5 devkits, 2 Xbox devkits, and 3 PC test machines. Build the test matrix: which scenarios require all three platforms simultaneously (minimum 6 accounts across 7 machines), which can be tested in platform pairs, and which of the four subsystems you test first given that a failure in input-based matchmaking is a cert risk while a failure in text filtering is a compliance risk.`
  },
  {
    // ca917a0f - was 6, "lacks the technical constraints needed to force a strong diagnostic answer"
    prefix: 'ca917a0f',
    text: `You are QA on a 5v5 ability-based competitive game using client-side hit detection with server reconciliation. Two players in a ranked match at Diamond tier report conflicting experiences: Player A (PC, 25ms ping, 0.1% packet loss, 144Hz monitor, raw mouse input) recorded a screen capture showing their sniper crosshair centred on Player B's head at the moment of fire, with a hit marker appearing for one frame before disappearing. No damage was dealt. Player B (PS5, 85ms ping, 0.8% packet loss, 60Hz output) used a dash ability and was behind cover on their screen when the shot was allegedly fired. The server replay (reconstructed from server-tick data at 64 ticks/second) shows the shot missing -- Player B's server-side position was 2.3 metres from the shot's trajectory at the tick the shot was registered. The game uses rollback netcode with a 150ms reconciliation window. The sniper rifle's hit detection uses a hitscan ray from the client's camera position at the client's reported firing tick, then the server rewinds other players' positions by the shooter's RTT to validate. The dash ability grants 200ms of invulnerability frames (12.8 server ticks) starting from the server tick when the ability activation is confirmed, not when the client pressed the button. Player A's network telemetry shows a 40ms jitter spike in the 500ms before the shot. Player B's telemetry shows the dash ability key was pressed 180ms before Player A's shot according to server timestamps. You have: server match logs with per-tick position, ability, and hit-detection data; both players' client telemetry; the replay file; the ability data sheet; and a local test environment with configurable latency injection, tick rate override, and ability timing visualisation. Determine whether this is (a) a reconciliation timing bug where the jitter spike shifted Player A's perceived rewind window, (b) an ability-timing bug where the invulnerability frames started late, (c) a hit detection bug where the hitscan ray used stale position data, or (d) working as intended where network conditions made the client prediction diverge from server state. Show the specific data points you check in what order to reach a definitive answer.`
  },
  {
    // f0e5290c - was 5, "phrased broadly enough that a candidate can answer from theory"
    prefix: 'f0e5290c',
    text: `You are QA on a free-to-play mobile gacha game launching a limited-time banner: a new SSR character at 1.2% pull rate, a featured SR at 5%, with the remaining 93.8% split across 40 other characters and items weighted by rarity tier. The banner runs 14 days across Japan (JOGA self-regulation: published rates must match actual rates; violation triggers industry body investigation), South Korea (Game Industry Promotion Act: drop rate table must be publicly accessible and updated within 24 hours of any change; penalties include service suspension), and the EU (upcoming loot box transparency requirements per the Digital Services Act amendments expected to mandate statistical fairness disclosure). The pity system guarantees an SSR within 90 pulls, with a 50% chance the SSR is the featured character; if the first pity SSR is not featured, the next pity SSR is guaranteed featured. Rate-up within the SSR tier gives the featured character 50% of the 1.2% SSR rate (0.6%) and distributes the other 0.6% across 8 other SSR characters. You have: a test server debug command that performs batch pulls (configurable: 1, 10, 100, 1000, 10000), access to the server-side RNG seed configuration (the game uses a Mersenne Twister PRNG seeded per-account at account creation), the drop rate table in the game's data files, analytics from a previous banner where the first pull in a new session had a 2.1% SSR rate instead of 1.2% due to a seeding bug (the PRNG was re-seeded on app launch instead of using the persistent account seed), and 3 days before the banner goes live. Design your test plan: how many pulls constitute a statistically meaningful sample (specify confidence level and acceptable margin of error), what chi-squared or equivalent test you apply to the results, how you specifically test for the previous seeding bug's recurrence, how you verify the pity system across the 50/100% featured guarantee boundary, and what compliance documentation you prepare per jurisdiction -- including what you do if your 100,000-pull test shows the SSR rate at 1.15% (within statistical noise at alpha=0.05 but below published rate).`
  },
  {
    // 12c1f68f - was 5, "too thin on constraints, can be answered with generic checklist"
    prefix: '12c1f68f',
    text: `You are QA on a 5v5 multiplayer hero game with 20 playable characters. A new support character's ultimate ability applies a 20% damage boost to all allies within a 15-metre radius for 8 seconds. Specific interactions to test: the buff stacks additively with the character's passive aura (10% boost, 8-metre radius, always active) for 30% total, but does NOT stack with another instance of the same ultimate (duplicate picks allowed in casual mode, blocked in ranked). The damage modifier is calculated server-side and applied on the next damage instance after the buff becomes active. Technical constraints: the game runs at 60 tick rate on dedicated servers; there is a measured 3-frame (50ms) delay between the VFX showing the buff active on the client and the server actually applying the damage modifier; the buff radius is measured from the casting position, not the character's current position -- meaning the character can cast and walk away, and the buff zone stays where they cast it. Edge cases from the design doc that the character designer flagged as "probably fine but please test": what happens when the ultimate is cast at the exact boundary of the passive aura (an ally at exactly 14 metres gets the ultimate buff but might not have the passive aura, depending on whether the passive range check runs before or after the ultimate range check in the same tick); what happens when an ally enters the buff radius during the 3-frame VFX delay; what happens when the buff expires on the exact tick that a projectile hits an enemy (does the projectile carry the buffed damage or unbuffed); and what happens when two support characters cast their ultimates on the same tick with overlapping radii. You have a local test server with bot spawning, tick rate adjustment, server-side damage logs with per-tick timestamps, and a network latency simulator. Design test cases for each of these edge cases -- not a generic coverage checklist, but the specific setup (character positions in metres, cast timing in ticks, expected damage values) that catches the most likely bugs.`
  },
  {
    // 306585e7 - was 5, "too broad without languages, UI constraints, VO/subtitle issues, cultural risks, or cert implications"
    prefix: '306585e7',
    text: `You are the sole localisation QA tester on a narrative RPG shipping on PS5, Xbox, PC, and Switch in 14 languages. The game has 45,000 dialogue lines with full VO in English, French, German, Japanese, and Brazilian Portuguese; text-only loc for Arabic, Simplified Chinese, Traditional Chinese, Korean, Spanish (Latin American), Italian, Polish, Russian, and Turkish. Your testing has found: (1) German text overflows the dialogue box in 23 instances -- German compound words are 30-40% longer than English, and the dialogue box has a fixed width of 480px with no auto-scaling; the font is 18px and cannot shrink below 16px per the UI lead's directive because the Switch renders at 720p handheld where smaller text becomes illegible. (2) Japanese dakuten diacritics (the ゛ marks on characters like が, ざ, だ) render incorrectly at the smallest UI text size (12px) on Switch only -- the glyphs overlap, making は indistinguishable from ば. This does not occur on PS5, Xbox, or PC at any resolution. The Switch-specific font renderer uses a different glyph atlas. (3) Arabic RTL text breaks in 6 instances where English item names are embedded in Arabic sentences -- the BiDi algorithm is inserting a direction override at the wrong boundary, causing the English text to appear at the start of the line instead of inline. (4) Brazilian Portuguese VO for a quest-critical NPC says "go to the Crimson Valley" (English name) while the subtitle reads "vá ao Vale Carmesim" (correct localised name), creating a VO/subtitle mismatch that Sony has explicitly flagged as a cert-fail condition in their localisation guidelines (TRC R4006). Two weeks before cert submission. Prioritise these issues with specific cert-risk reasoning, identify what additional localisation risks you proactively test for (considering that you have 9 text-only languages that have had zero testing), and specify which issues are cert blockers versus ship-with-known-issue candidates and why.`
  },
  {
    // 4baf7df4 - was 5, "needs concrete systems, telemetry, simulation access, or exploit constraints"
    prefix: '4baf7df4',
    text: `You are QA on a free-to-play mobile strategy game with four currency types: gold (soft, earned through gameplay at approximately 500/hour at level 30), gems (hard, USD 0.99 per 100 or earned at approximately 10/day from daily quests), energy (refills 1 unit per 6 minutes, cap of 120, used for campaign missions at 8-15 per mission depending on difficulty), and seasonal event tokens (earned 5 per event mission, expiring 14 days after the event ends, exchangeable for exclusive units and cosmetics at rates from 50 to 500 tokens). The game has 60 progression levels; design intent is level 20 at 14 days and level 60 at 6 months. You have: a debug menu that sets player level, grants currencies, and adjusts server time by arbitrary increments; a telemetry dashboard showing live economy metrics (gold inflow/outflow per level bracket, gem purchase conversion rates, energy refill gem-spend rates, average session length); and the design team's economy spreadsheet with intended pacing curves. The game has a trade system where players can exchange items (but not currencies directly) in a marketplace with a 10% gold tax on sales. Here is the exploit the designers are worried about: event tokens can be used to buy exclusive crafting materials, those materials can be crafted into tradeable items, and those items can be sold on the marketplace for gold, which can be used to buy gem-discounted bundles during promotions -- creating a token-to-gold-to-discounted-gem conversion path that the designers did not model. You cannot play for 6 months. Walk through how you validate the economy across the full progression arc in under two weeks of testing: how you use the debug tools to simulate level 10/20/30/40/50/60 states, what specific gold inflation checkpoints you measure at each tier, how you test the energy wall frustration curve (at what level does a player hit zero energy before completing the daily quest set), and how you test the token-to-gem conversion exploit -- including calculating the effective gem-per-USD exchange rate through this path versus the direct purchase rate.`
  },
  {
    // 65f78e4f - was 5, "needs party sizes, cross-play, region, skill rating, queue time constraints"
    prefix: '65f78e4f',
    text: `You are QA on a 3v3 competitive mobile game launching in NA, EU, and Asia-Pacific with cross-region play. The matchmaking system: SR ranges 0-5000 with role-specific ratings (tank, damage, support); solo queue and pre-made parties of 2 or 3; each team needs exactly one of each role. Rules: solo players should not face full 3-stacks unless queue time exceeds 120 seconds; SR difference within a match must not exceed 500 SR; cross-region matches are enabled when same-region queue time exceeds 60 seconds, with a UI ping indicator. The progressive relaxation algorithm: at 0-30 seconds, strict SR (500 max difference) and same-region only; at 30-60 seconds, SR expands to 750; at 60-90 seconds, cross-region enabled; at 90-120 seconds, SR expands to 1000 and 3-stack vs solo allowed; at 120+ seconds, SR expands to 1500. Asia-Pacific off-peak (2-6am JST) has an estimated 200 concurrent players versus NA/EU peak of 8,000. You have a staging server with configurable matchmaking parameters, a bot system simulating up to 200 concurrent players with configurable SR, region, role, and party size, and server-side matchmaking logs with per-match queue time, SR spread, region composition, and party composition. Test these specific failure scenarios: (1) What happens when the only support player in the Asia-Pacific queue at 4am JST is SR 4500 and all available tank/damage players are SR 1000-2000? Does the system create a 3500-SR-spread match or leave the support player in queue indefinitely? (2) When a 2-stack queues as tank+damage and the only available support is in a different region at 55 seconds queue time (5 seconds before cross-region enables), does the match pop at 60 seconds or does the timer reset when the support enters the candidate pool? (3) A 3-stack of SR 3000 players queues at the same time as three solo SR 3000 players of matching roles -- does the system correctly prefer the 3-solo match or does it create the 3-stack-vs-solo match despite being within the no-3-stack window? Build the test plan with specific bot configurations for each scenario and the pass/fail criteria for each.`
  },
  {
    // 9303edb9 - was 6, "would benefit from scene complexity, player count, audio budget, or platform-output constraints"
    prefix: '9303edb9',
    text: `You are QA on a 32-player battle royale on PC, PS5, and Xbox. The audio engine has 64 simultaneous sound channels with priority: player weapons (highest), nearby ability effects (second), environmental audio (third), distant combat (fourth). When the 64-channel limit is hit, the engine culls lowest-priority sounds. Spatial audio: PC uses the engine's built-in HRTF, PS5 uses Tempest 3D Audio, Xbox uses Windows Sonic. Three issues from a playtest with 28 players in the final circle (roughly 80-metre diameter area): (1) Footsteps of enemies within 10 metres became inaudible during heavy combat. The audio debugger showed all 64 channels occupied: 22 weapon sounds, 18 ability effects, 14 environmental, 10 distant combat. Footsteps are categorised as "environmental" (priority 3) and were being culled in favour of distant combat sounds (priority 4) that were louder. This means the priority system is not working as documented -- either footsteps are miscategorised or the culling is using volume as a secondary sort that overrides priority. (2) A grenade explosion behind the player at 220 degrees sounded like it came from 130 degrees (left) on PS5, but positioned correctly on PC and Xbox. The PS5 Tempest implementation uses the game's object positions, but the grenade's audio emitter is attached to the explosion VFX particle system, not the grenade projectile -- and on PS5, the particle system's world position updates one frame later than on PC/Xbox due to the PS5's async compute pipeline. (3) When a player is downed and enters spectator mode, all spatial audio collapses to stereo. The spectator camera does not have an audio listener component attached -- it was added to the player character but not to the spectator camera prefab. Walk through how you reproduce each issue (specifying player count, combat density, and platform configuration needed), what audio debugger data you capture as evidence, and how you verify fixes given that each platform uses a different spatial audio backend.`
  },
  {
    // c97df449 - was 5, "invites a rehearsed checklist rather than a scenario-specific build-verification decision"
    prefix: 'c97df449',
    text: `You are QA on a cross-platform multiplayer game on Steam, Epic, PS5, and Xbox Series X|S. A build arrives Monday morning -- candidate for Wednesday's publisher milestone demo at 3pm. This build includes a 40-file merge from the networking branch (changes to matchmaking, host migration, and party system) and the first integration of seasonal content (3 new maps, 2 new characters with 4 abilities each, and 15 cosmetic items including 3 that are platform-exclusive -- one PS5, one Xbox, one PC). Your smoke test must cover all four platform SKUs in under 90 minutes with one tester. Platform-specific concerns: Steam and Epic have different achievement SDKs and the seasonal content adds 8 new achievements; Steam cloud save and Epic cloud save use different serialisation formats and this build changes the save structure to include seasonal progression data (backward compatibility with pre-season saves is required); the PS5 build has Activity Cards for the new seasonal challenges that need to render correctly in the system UI; the Xbox build must show the new characters in the Game Hub's character gallery tile which pulls from a metadata manifest that was last updated two builds ago. The networking merge introduces a new party-join flow that changes how platform invites are converted to game-session joins -- this is the most likely source of regression and touches every platform differently (PSN invite, Xbox Game Invite, Steam friend invite, Epic Social Overlay invite). You have 1 PS5 devkit, 1 Xbox devkit, and 1 PC with both Steam and Epic installed. Define your smoke test with exact check order per platform, specifying: what you check first on each SKU (and why that order), how you verify the 3 maps are loaded without a full content pass, the specific networking regression check you run given the party-invite changes, at what point you fail the build (what is the fail-fast criterion that blocks regression testing), and how you communicate a partial pass to the producer -- e.g., "Steam and PS5 pass, Xbox invite flow broken, Epic untested due to time."`
  },
  {
    // ef679fdd - was 5, "subjective feel investigation needs concrete combat mechanics, latency/frame data, or comparison targets"
    prefix: 'ef679fdd',
    text: `You are QA on a third-person melee action game on PS5 and PC. A 15-person playtest reports combat feels "sluggish" and "unresponsive" -- specifically, light attacks feel delayed and heavy attacks feel like the player is locked in animation too long. Engineering's data: light attack input-to-first-animation-frame is 3 frames (50ms at 60fps), heavy attack is 8 frames (133ms). The combat lead cites Devil May Cry 5 (light: 4 frames) and Monster Hunter World (heavy: 10-15 frames) and says the game is within range. But you investigate further and find these specific mechanical issues: (1) The input buffer window is 4 frames at the END of recovery animation -- button presses during frames 1 through recovery-minus-4 are silently dropped. Recovery on light attacks is 12 frames, meaning frames 1-8 of recovery drop inputs entirely. The playtest input telemetry shows 34% of light attack button presses occur during the dead zone (frames 1-8 of recovery), meaning 1 in 3 intended combo inputs are lost. (2) Hit-stop (freeze frame on impact) is 2 frames for light attacks and 0 frames for heavy attacks. DMC5 uses 3-4 frames of hit-stop on light and 6-8 on heavy. The absence of hit-stop on heavies makes them feel like they are not connecting -- there is no impact feedback from the animation system. (3) The camera has zero response to attacks -- no shake, no subtle push, no FOV shift. DMC5 shifts FOV by 2 degrees on heavy attacks and adds a 0.3-degree camera shake on light hits. (4) The DualSense haptic feedback on PS5 fires 4 frames AFTER the visual hit VFX, creating a perceptible desync between seeing and feeling the hit. You have: a frame-by-frame replay tool, the animation state machine debugger with per-state frame data, input telemetry from the 15 playtesters (button timestamps, action outcomes, dropped inputs), and a 240fps capture setup. Build the evidence package: what measurements you take, what comparison footage you capture from DMC5 and Monster Hunter at 240fps as reference, how you visualise the input dead zone to make it immediately legible to the combat designer, and how you structure the bug report so it is data-driven rather than subjective opinion.`
  },
  {
    // 6e6f3634 - was 6, "needs a sharper game-release decision point"
    prefix: '6e6f3634',
    text: `You are QA lead on a 50-person studio's multiplayer title, four months from ship on PS5, Xbox, and Switch. The production director asks you to present a 10-minute "State of Quality" update at the all-hands. Your data: 142 open bugs (18 critical, 34 major, 90 minor); bug fix turnaround averages 3.1 days but the 18 criticals average 8.2 days; 12 bugs are older than 30 days including a cert-blocking memory leak on Switch (the Switch build exceeds Nintendo's 4GB memory budget by 200MB in the final boss arena -- the only level that breaches the limit and the most likely candidate for Nintendo's automated memory audit); test coverage is at 74% of planned cases but the untested 26% includes all cross-play party scenarios, the entire Battle Pass progression system, and the Switch-specific performance profile. The studio has spent 3 of its 4 planned QA sprints. A newly discovered exploit lets players duplicate crafting materials via a specific menu sequence (open crafting menu, start crafting, open inventory before the crafting animation completes, drag the input material to a different slot -- the material is consumed by the craft AND retained in the new slot). This exploit has been found by the community in the open beta and is being shared on Discord. The audience: 6 engineers, 5 artists, 4 designers, 2 producers, the studio head who tends to react emotionally to bug counts, and the publishing producer (remote) who will relay your update to the publisher's greenlight committee. How do you structure 10 minutes so engineering gets the technical data needed to plan fix sprints, production gets the schedule risk assessment for the remaining QA sprint, the studio head gets a ship-readiness picture calibrated to cert risk rather than raw bug count, and the publisher's representative gets the information needed to not escalate to the greenlight committee -- and what do you explicitly omit or defer to a follow-up to stay within 10 minutes?`
  },
  {
    // af8c19b4 - was 5, "needs a concrete feature, ship gate, defect class, or platform consequence"
    prefix: 'af8c19b4',
    text: `You are QA lead on an online co-op RPG shipping on PC via Steam and Epic tomorrow at 10am UTC. You were assigned to test the new crafting and trading systems: 6 crafting stations (forge, alchemy, cooking, tailoring, woodworking, enchanting), 140 recipes total, and player-to-player trading with a server-side transaction log. After a full day you spent 80% of your time on forge and trading because: the forge had a cascading bug where combining two rare-tier materials produces an item with negative stat values (specifically, combining Infernal Ore + Starlight Dust yields a weapon with -15 attack power, which the damage calculation interprets as healing enemies on hit); the trading system had a race condition where two players accepting a trade on the same server tick duplicates both items. You filed 14 bugs total: 6 forge recipe bugs (negative stats, missing output items, wrong rarity tier on output), 5 trading bugs (the duplication race, a desync where one player sees the trade complete but the other does not, three UI issues), and 3 cross-system bugs (crafted items cannot be traded, enchanted items lose enchantments when traded, trading during a crafting animation cancels the craft but consumes the materials). The other 5 stations have been smoke-tested only: you ran one recipe from each category, verified the output existed, and moved on. Untested: crafting with a full inventory (what happens to the output?), crafting during server lag (is there a timeout?), recipe unlocking at level boundaries (level 20/30/40 recipes), crafting output when input materials have enchantment modifiers (does a +10% damage enchantment on ore affect the weapon's base stats?), and bulk crafting (queue 10 of the same recipe). It is 8pm, ship is in 14 hours, and you have 4 more working hours. What do you test in those 4 hours (prioritised by exploit risk versus cosmetic risk), what risk brief do you write for the producer covering the untested surface, and what specific data do you include so the ship/delay decision is evidence-based -- including your assessment of whether the forge negative-stats bug and the trade duplication bug are ship-blocking or can be hotfixed within the first 24 hours?`
  },
];

(async () => {
  let applied = 0;
  for (const r of REWRITES) {
    const result = await pool.query(
      "UPDATE interview_question_bank SET question_text = $1, updated_at = NOW() WHERE id::text LIKE $2 RETURNING id",
      [r.text, r.prefix + '%']
    );
    if (result.rows.length) {
      console.log('APPLIED:', result.rows[0].id);
      applied++;
    } else {
      console.log('NOT FOUND:', r.prefix);
    }
  }
  console.log('\nTotal applied:', applied, 'of', REWRITES.length);
  await pool.end();
})();
