require('dotenv').config();
const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const REWRITES = [
  {
    // 2dccb4df - R1 score 6, "bloated, asking for all 40 classifications is a reading-comprehension endurance test"
    // Fix: cut the 40-classification demand, focus on the 12 engineering slots and the hardest triage calls
    prefix: '2dccb4df',
    text: `You are QA lead on a free-to-play PvP shooter submitting to Sony and Microsoft on Tuesday. Engineering can fix 12 of 40 open bugs. You have already triaged the easy calls: the four crashes (two PS5 map-transition crashes, one Xbox party-invite crash, one PC anti-cheat crash) are mandatory fixes because Sony TRC and Microsoft XR require zero crash-to-dashboard -- that is 4 of your 12 slots gone. The remaining 8 slots must be allocated across these six competing bugs, each with a different risk profile: (1) a wall-breach exploit on one competitive map posted on Reddit with 2,000 upvotes and a reproduction video -- not a cert blocker but will generate refund requests and streamer coverage on launch day; (2) a UI overlap that hides the real-money purchase confirmation button on ultrawide monitors at 21:9 and 32:9, affecting an estimated 8% of PC players -- the monetisation team says this could trigger refund cascades; (3) an audio desync on all platforms when more than 8 players use abilities simultaneously -- affects gameplay clarity but no cert risk; (4) a weapon dealing 0 damage on headshots when the target is on a ladder -- rare but reproducible, competitive integrity issue; (5) an incorrect hitbox on one character's crouch animation making headshots register as body shots -- affects every match involving this character; (6) a memory leak in the spectator camera reaching 800MB after 40 minutes -- affects tournament broadcasts and streamers but not ranked play. You can only fix 8 of these 6 -- wait, you have 8 slots for 6 bugs, so you can fix all 6, but that leaves only 2 slots for the remaining 30 minor bugs. Alternatively, you could fix 5 of the 6 and use 3 slots on the highest-risk minor bugs. Which of the six do you deprioritise if you take that trade, why, and what does the risk acceptance note to the platform holders say about the bug you ship with?`
  },
  {
    // 48781dad - R1 score 6, "tests communication packaging rather than hard QA craft"
    // Fix: make the core challenge the anti-cheat evidence dispute, not the presentation format
    prefix: '48781dad',
    text: `You are QA on a multiplayer shooter four months from console cert submission. Your testing shows the anti-cheat system kicks legitimate players on Wi-Fi connections with packet loss above 2%, which telemetry from the open beta suggests affects 12% of the console player base. The engineering lead disputes your findings: the anti-cheat vendor's documentation specifies a 5% packet loss threshold, and the lead says your test methodology is wrong because you used the devkit's network simulation tool, which does not model real-world packet loss patterns (burst loss vs. uniform loss). You have packet captures from 8 test sessions on PS5 devkits showing disconnections starting at 2.1% uniform packet loss. The vendor's SDK has no configurable threshold on the client side -- it is server-side, set to a value the vendor manages. You do not have access to the vendor's server configuration. The engineering lead is now cc'ing the studio director on emails saying QA is "blocking the anti-cheat integration" with "unreliable test data." You believe the vendor's documentation describes a different threshold than what is actually deployed, possibly because the vendor tightened it in a recent update. Walk through: what additional evidence you gather to resolve the 2% vs 5% dispute definitively (not opinion, data), how you test for burst packet loss versus uniform to address the engineering lead's methodology critique, what you request from the vendor to verify the deployed threshold, and -- if the vendor confirms 2% is intentional -- what you recommend as the fix, given that weakening anti-cheat will increase cheating and keeping it will kick 12% of console players.`
  },
  {
    // 58bef60b - R1 score 6, "crams too many things into one over-wide answer"
    // Fix: narrow to the networking regression risk and the late-breaking desync decision
    prefix: '58bef60b',
    text: `Your studio is submitting a patch for a live multiplayer arena brawler on PS5, Xbox, and PC. The patch includes a new melee assassin character whose dash ability had its server reconciliation changed: previously the server trusted the client's reported position during dashes, now it performs server-side pathfinding validation. This fix was made because the old approach let players dash through walls on high-latency connections. You have 9 hours before the cert submission window closes, one junior tester who has never tested cert, a staging server supporting 8 simultaneous players, and 2 devkits per platform. At 3pm (4 hours remaining), you discover a desync bug: when the assassin dashes through their own smoke bomb ability while being hit by a melee attack, the server-side pathfinding validation rejects the dash endpoint (because the smoke bomb's area-denial flag incorrectly blocks allied pathfinding), but the client has already played the dash animation. The result: the assassin rubber-bands back to the pre-dash position on the attacker's screen but appears at the post-dash position on their own screen for 400ms. This is reproducible at roughly 1-in-3 attempts when all three conditions align (dash, smoke bomb, incoming melee on the same tick). You have 4 hours. The cert submission includes the dash reconciliation fix as a highlighted change because the wall-dash exploit was a known issue the platform holders flagged. Three options: (1) submit with the desync bug and document it as a known issue, risking cert rejection because the highlighted fix introduces a new defect; (2) revert the dash reconciliation fix entirely, which re-enables the wall-dash exploit; (3) ask engineering for a targeted fix to the smoke bomb's pathfinding flag, which they estimate at 2 hours, leaving you 2 hours of testing on a code change made under pressure. Which do you recommend and why?`
  },
  {
    // 4baf7df4 - R1 score 6, "full-progression validation too broad, rewards spreadsheet fluency"
    // Fix: narrow to the token-to-gem exploit and one specific economy breakpoint
    prefix: '4baf7df4',
    text: `You are QA on a free-to-play mobile strategy game. The designers have identified a potential exploit chain they want you to verify: seasonal event tokens (earned at 5 per event mission, 14-day expiry) can purchase exclusive crafting materials (50 tokens for a Starforged Ingot), those materials can be crafted into a Starforged Blade (tradeable), and the blade sells on the player marketplace for approximately 8,000 gold (after 10% tax). During promotional events, a gem-discounted bundle costs 5,000 gold + 50 gems instead of the normal 500 gems. This creates a conversion path: tokens → materials → tradeable item → gold → discounted bundle. The designers think this is theoretical. You have a debug menu that grants currencies, sets player level, and adjusts server time. Your task is to execute this exploit chain end-to-end on the test server and calculate the effective conversion rate. Specifically: (1) How many event missions does a player need to complete to accumulate enough tokens for one Starforged Ingot? (2) How long does the crafting-to-marketplace-to-sale cycle take in real time, accounting for the marketplace listing period (items list for 24 hours before expiring)? (3) What is the effective gem-per-USD exchange rate through this path versus the direct purchase rate of 100 gems per USD 0.99? (4) Does the exploit scale -- can a player run 10 parallel marketplace listings, and does the marketplace have a listing limit per player? (5) If the conversion path yields gems at less than 50% of the direct purchase rate, is it actually an exploit worth fixing, or is the time investment so high that only bots would use it? Show your test setup, the actual numbers from your test run, and your recommendation on whether this needs a fix before the next promotional event in 9 days.`
  },
  {
    // c97df449 - R1 score 6, "scope so broad a polished process answer could hide shallow platform knowledge"
    // Fix: narrow to the networking regression and the platform-specific invite flow
    prefix: 'c97df449',
    text: `You are QA on a cross-platform multiplayer game on Steam, Epic, PS5, and Xbox. A Monday morning build is the candidate for Wednesday's publisher demo. The build includes a 40-file networking merge that changes how platform invites are converted to game-session joins. This is the highest regression risk: the invite flow is different on each platform -- PSN invites go through the PlayStation Activity system, Xbox uses Game Invite notifications, Steam uses the Steam Overlay friend invite, and Epic uses the Social Overlay. Each path has a different handshake sequence between the platform SDK and the game's session service. In the last build, a networking merge broke Xbox party invites for 3 days before anyone noticed because the Xbox invite path was not in the smoke test. You have 90 minutes, 1 PS5 devkit, 1 Xbox devkit, and 1 PC with both Steam and Epic installed. You cannot test all four invite paths thoroughly -- each requires creating a party, sending an invite, accepting, verifying session join, and then testing disconnect/reconnect during the session. A thorough test of one platform's invite flow takes 15-20 minutes. You have time for roughly four full tests. Which four tests do you run, in what order, and why? Specifically: do you test all four platforms' invite flows (one pass each, no regression depth), or do you test two platforms' invite flows deeply (invite + disconnect + reconnect + cross-play party) and skip two? If you skip two, which two and what risk does that carry for the Wednesday demo? And at what point in the 90 minutes do you stop testing and declare pass/fail -- what is the specific failing condition that blocks the demo?`
  },
  {
    // 6e6f3634 - R1 score 6, "leans into executive communication rather than testing decisions"
    // Fix: make it about the Switch memory leak triage and the exploit fix priority decision
    prefix: '6e6f3634',
    text: `You are QA lead on a multiplayer title four months from ship on PS5, Xbox, and Switch. Two critical issues surfaced this week and you must decide which one engineering works on first -- they can only tackle one in the current sprint. Issue 1: the Switch build exceeds Nintendo's 4GB memory budget by 200MB in the final boss arena. This is the only level that breaches the limit. Nintendo's automated certification test runs a memory audit on every level and will fail the submission if any level exceeds the budget. The final boss arena has 4 unique VFX systems, 12 destructible objects, and a phase-2 boss model that alone uses 380MB -- nearly 10% of the total budget. The rendering engineer says the boss model can be optimised to 280MB by reducing bone count, but that requires re-rigging 40 animations, which is 3 weeks of animator time. Alternatively, the VFX systems can be simplified for Switch only, saving an estimated 150MB, but this has not been prototyped and the VFX artist is on a different project until next month. Issue 2: a crafting material duplication exploit has been found by the community in the open beta and is being shared on Discord with step-by-step instructions (open crafting menu, start crafting, open inventory before the animation completes, drag the input material to a different slot). The duplicated materials persist through server restart. The exploit undermines the game's economy -- rare materials that should take 20 hours to farm can be duplicated in 2 minutes. The server team says the fix is straightforward (lock the inventory during the crafting animation) but requires testing across all 6 crafting stations and 140 recipes to verify no legitimate crafting flow breaks. Which issue gets the sprint, which waits, and what is the production consequence of each choice? If you choose the memory fix, what specific mitigation do you recommend for the exploit in the interim (server-side monitoring, disabling crafting, rate-limiting material gains)? If you choose the exploit fix, what is your cert timeline risk for the Switch memory issue?`
  },
  {
    // af8c19b4 - R1 score 6, "can become generic late-stage prioritisation"
    // Fix: focus specifically on the ship-block assessment for the two critical bugs
    prefix: 'af8c19b4',
    text: `You are QA on an online co-op RPG shipping on PC via Steam and Epic tomorrow at 10am UTC. You have found two critical bugs that are not yet fixed. Bug 1: combining Infernal Ore + Starlight Dust at the forge produces a weapon with -15 attack power. The game's damage calculation treats negative attack power as healing -- a player wielding this weapon heals enemies on hit. The weapon is tradeable, meaning one player can craft it and trade it to others. In PvP, a griefer could equip this weapon and heal the opposing team. The forge recipe uses two rare-tier materials that take approximately 8 hours of gameplay to farm, so the bug requires significant investment to trigger, but the weapon persists once crafted. Bug 2: when two players accept a trade on the same server tick (measured: roughly 1-in-15 simultaneous accepts during your testing), both players receive copies of both items -- a full item duplication. The duplication is server-authoritative and persists through restart. In a game with player-to-player trading and a marketplace, this is a currency generation exploit: players can duplicate the most valuable item and sell copies. Engineering estimates 4 hours for Bug 1 (clamp attack power to minimum 0 in the damage formula) and 6 hours for Bug 2 (add a transaction lock with a 500ms accept window). Ship is in 14 hours but the engineering team is available for only 8 hours of that. You can fix one bug completely and start the other. Which do you fix first, why, and can either ship with a server-side mitigation instead of a client patch -- specifically, could you disable the forge recipe server-side without a client update, and could you add a server-side trade cooldown as a stopgap?`
  },
];

(async () => {
  let applied = 0;
  for (const r of REWRITES) {
    const result = await pool.query(
      "UPDATE interview_question_bank SET question_text = $1, updated_at = NOW() WHERE id::text LIKE $2 RETURNING id",
      [r.text, r.prefix + '%']
    );
    if (result.rows.length) {
      console.log('APPLIED:', result.rows[0].id);
      applied++;
    } else {
      console.log('NOT FOUND:', r.prefix);
    }
  }
  console.log('\nTotal applied:', applied, 'of', REWRITES.length);
  await pool.end();
})();
