require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const REWRITES = [
  // 8f6e9428 -- Codex: "save exactly 0.4ms conflicts with pairwise savings" (mechanical math flaw)
  // Fix: correct the arithmetic so the savings add up properly
  {
    prefix: '8f6e9428',
    text: `You are Lead Animator on a third-person multiplayer game in Unreal 5 with motion matching. Animation is consuming 4.2ms per frame on PS5. Engineering needs you to cut 1.0ms, bringing your budget to 3.2ms. You profile in Unreal Insights and find three cost centres: (A) motion matching pose search across a 2,400-clip database takes 1.1ms -- halving the database to 1,200 clips saves 0.5ms but removes all directional start/stop variants, making locomotion transitions snappier but losing weight; (B) blend tree evaluation on 16 simultaneous active blend nodes takes 0.8ms -- collapsing to 8 nodes saves 0.4ms but eliminates additive breathing and secondary cloth motion on the player character; (C) skeletal mesh skinning on 8 visible characters with 150-bone skeletons takes 1.2ms -- reducing to 100 bones saves 0.4ms but requires removing all twist bones from forearms and calves, causing candy-wrapper deformation on extreme rotations. Any single option is insufficient. Choose two. State which one you refuse to touch and the specific visual degradation that makes it unacceptable in a shipped multiplayer title. For your two choices, state the combined savings, whether it meets the 1.0ms target, and which you implement first -- the one with the higher visual cost or the one with the lower visual cost -- and why the order matters for team buy-in.`
  },

  // c4bb3587 -- Codex: "junior-credit component drifts into team-culture"
  // Fix: remove the credit question, replace with a concrete colour-space decision
  {
    prefix: 'c4bb3587',
    text: `You are Lead Concept Artist on a horror game. Your locked colour palette for horror levels is desaturated cool tones: blue-grey walls (HSB 210/15/35), green-grey floors (HSB 150/10/30), neutral fog (HSB 0/0/45). The style guide has been followed by 4 artists across 6 environments. A safe room concept arrives using the same palette -- it reads as another horror space, not a relief zone. The player needs to feel the transition from danger to safety, but you cannot use warm hues (the style guide bans saturation above 20 and hue shifts outside the 140-220 range). Three approaches within the locked palette: (A) increase value (brightness) from 35 to 60 on walls, keeping hue and saturation identical -- the room feels lighter but the material read shifts from aged stone to plaster, conflicting with the architecture; (B) shift the floor hue from 150 (green-grey) to 200 (blue-grey), unifying walls and floors into a single cool tone that reads as calm rather than foreboding -- subtle but may not register as "safe" for most players without additional cues; (C) break the no-warm-hue rule for exactly one prop (a lit fireplace or candle cluster) at maximum 5% screen coverage, creating a focal warm accent that signals safety without contaminating the room's overall cool palette -- effective but sets a precedent that the locked palette has exceptions. Choose one. Rule out one with a specific visual or production consequence. State the HSB values of the dominant wall colour in your chosen safe room and how it differs from the adjacent horror corridor by more than just brightness.`
  },

  // d4e759e8 -- Codex: "deliberately planting a flaw tests management not concept art"
  // Fix: replace with a pure concept art craft question about visual hierarchy in prop design
  {
    prefix: 'd4e759e8',
    text: `You are Lead Concept Artist on a multiplayer game set in a medieval market district. You have designed 12 hero props that define the market's visual identity: blacksmith forge, tanner's rack, fishmonger's stall, apothecary cart, and 8 others. The environment art lead reports that in-engine, players cannot distinguish the blacksmith forge from the tanner's rack at the default 40-metre camera distance -- both read as a dark rectangular shape with a vertical element. At 10 metres the materials differentiate them (orange embers vs brown leather), but the level designer uses these props as navigation landmarks and needs them identifiable at distance. You must redesign one of the two props to break the silhouette collision. Three approaches: (A) add a tall chimney to the blacksmith forge extending 3 metres above the stall roofline -- instantly differentiates the silhouette at any distance but adds a vertical element that may occlude player sightlines in competitive play; (B) change the tanner's rack from a rectangular frame to a curved arch with hanging pelts -- differentiates the shape but requires the environment artist to rebuild the modular snap points (the rack was designed to tile against walls); (C) keep both silhouettes identical but assign them to different biome colour palettes (warm for blacksmith, cool for tanner) -- differentiates by colour but fails for colourblind players and breaks your single-biome material palette. Choose one. Rule out one with a specific production or accessibility failure. State the minimum silhouette differentiation test you would run on all 12 hero props before they enter production: what image size, what background, and what pass/fail criterion.`
  },

  // 53f9e9c2 -- Codex: "primary cause is underdetermined, risks testing memorised pipeline preferences"
  // Fix: make it a concrete lighting correction task, not a diagnosis with uncertain root cause
  {
    prefix: '53f9e9c2',
    text: `You are a Snr Lighting Artist on a stylised action game in Unreal Engine 5 using Lumen. The character team delivers 6 hero characters for in-engine approval. Each character was validated in Marmoset Toolbag. In-engine, all 6 show the same problem: skin tones are desaturated by roughly 20%, metallic armour specular highlights are 2 stops brighter than intended, and cloth materials read as plasticky. You confirm the materials are authored correctly (roughness, metallic, albedo values match the Marmoset setup). The issue is your scene lighting. Your current setup: a single directional light at intensity 10 lux, colour temperature 6500K (neutral daylight), a Lumen sky light at intensity 0.5 with a flat grey HDRI, and ACES tonemapping in the post-process volume. Three lighting corrections: (A) replace the flat grey HDRI with a warm outdoor environment HDRI that provides indirect fill at varied angles -- restores skin warmth through coloured bounce light but now every character must be approved against a specific HDRI that may not match the actual game environments; (B) reduce the directional light intensity from 10 to 6 lux and raise the sky light from 0.5 to 1.5 -- lowers the direct-to-indirect ratio, reducing the blown-out specular peaks but also flattening the dramatic lighting contrast the art director approved; (C) switch from ACES tonemapping to a custom filmic curve with a higher midtone shoulder -- preserves skin saturation in the midtones where ACES crushes it, but requires the entire game's post-process to be re-graded for consistency with all other levels. Choose one. Rule out one with a specific downstream cost. State whether you build this corrected setup as the permanent character approval scene for all future characters, and what you lock (light intensity, HDRI, tonemapper) versus what you allow artists to adjust per-character.`
  },

  // 709efb7d -- Codex: "answer feels embedded in option wording"
  // Fix: reframe with less leading option descriptions, force the candidate to identify the trade-off
  {
    prefix: '709efb7d',
    text: `You are a Snr Lighting Artist on a military shooter in Unreal Engine 5. The map was relit from midday to dusk (low-angle orange sun, 3200K colour temperature). All 200+ environment material instances were authored for midday lighting (5500K neutral). Post-relight, three material categories are broken: (A) concrete surfaces (roughness 0.7) show visible wet-looking specular streaks from the low sun angle; (B) metallic surfaces (roughness 0.3) have lost their metallic colour response -- they read as tinted orange plastic because the strong warm key light overwhelms the metal's reflective colour; (C) wet asphalt (roughness 0.15) is indistinguishable from dry asphalt because every surface now has strong directional specular from the low sun. You cannot ask the environment artist to re-author 200+ instances. You can adjust only: the directional light (intensity, angle, colour), the sky light (intensity, colour), and the post-process volume (exposure, colour grading, screen-space reflections). Propose a single lighting adjustment that fixes the worst of the three problems. State which problem you are fixing, what specific setting you change and to what value, and why this fix does not solve the other two problems. Then state which of the remaining two problems you escalate to the environment artist for a material-side fix, and the specific roughness adjustment you request (which direction and by how much).`
  },

  // 53b8c732 -- Codex: "asking for exact contrast ratio in stops is arbitrary"
  // Fix: remove the arbitrary number ask, replace with a concrete A/B validation test
  {
    prefix: '53b8c732',
    text: `You are a Snr Lighting Artist on a multiplayer map in Unreal 5 with Lumen. A cave-to-exterior transition uses a warm 5500K directional key and two rect lights for bounce at the cave mouth. The art director says the cave interior is too dark. Adding a sky light costs 1.5ms on the Lumen budget and reduces enemy silhouette readability at 30 metres -- enemies in shadow become harder to distinguish from the environment. Three alternatives: (A) add a single non-shadow-casting point light (radius 15m, intensity 2000 lumens, 4500K) at the cave centre -- raises the ambient by filling from a single source, but creates a visible artificial light pool on the cave floor with no apparent source object, breaking the realistic lighting motivation; (B) increase the two existing rect light bounce intensities from 500 to 1500 lumens each and widen their cone from 60 to 120 degrees -- uses existing sources but the doubled bounce intensity causes colour bleed, staining the cool blue-grey stone walls with warm orange reflections; (C) place 4 small emissive rock crystal props (mesh emissive, intensity 800) at eye-level around the cave as motivated practical light sources -- adds believable light sources with zero dynamic light cost but requires environment art to create and place the crystal props (2 days of art time not in the budget). Choose one. Rule out one with a specific visual failure that would be visible in gameplay footage. State the validation test you run after implementing your fix: what camera position, what you are checking (enemy character visibility, colour accuracy, or performance), and what result causes you to revert.`
  },

  // e552967c -- Codex: "material, draw-call, and texture-memory assumptions are muddled"
  // Fix: simplify the numbers to be internally consistent, tighten the core trade-off
  {
    prefix: 'e552967c',
    text: `You are a Snr Technical Artist on an open-world RPG in Unreal Engine 5, shipping on PS5. Per-scene draw call budget: 2,000. World tiles are 500m x 500m. You estimate 600 props per tile at average density. Each unique material adds 1 draw call. The terrain system uses 200 draw calls. Characters and VFX reserve 300. That leaves 1,500 draw calls for props. If every prop has a unique material, you use 600 draw calls -- within budget. But the environment team wants per-prop texture sets at 2048x2048 resolution (albedo + normal + ORM = 3 textures per prop). At 2048 resolution, 600 props consume 28GB of texture memory. PS5 texture streaming budget for a tile: 2GB. You must reduce texture memory by 93% while staying under 1,500 prop draw calls. Three strategies: (A) shared material atlases: 8 texture atlases at 4096x4096, each covering ~75 props by material type (wood, stone, metal, etc.) -- reduces to 8 unique materials (8 draw calls) and ~400MB texture memory, but each prop's UV space is limited to roughly 512x512 effective resolution within the atlas, making close-up detail muddy; (B) per-prop materials at 512x512 textures -- keeps 600 draw calls (within budget) and reduces texture memory to ~1.7GB (within budget), but 512 textures look blurry on any prop larger than 2 metres viewed within 5 metres; (C) virtual texturing: a single streaming virtual texture atlas at runtime resolution, with 2048 source textures streamed on demand -- near-unlimited effective resolution with minimal resident memory, but virtual texturing on PS5 adds 0.8ms per frame and produces visible tile pop-in during fast camera movement. Choose one. Rule out one with a specific visual or performance failure. State the enforcement mechanism you build to catch an artist who submits a prop at 2048 resolution in violation of the spec.`
  },

  // 361563e1 -- Codex: "more prioritisation exercise than craft test, option A contradicts stated bug"
  // Fix: replace with a pure tool architecture question about pipeline performance
  {
    prefix: '361563e1',
    text: `You are a Snr Technical Artist on an open-world RPG in Unreal Engine 5. You built a Python foliage placement tool for biome-aware vegetation scattering in-editor. The tool has three performance bottlenecks exposed by profiling: (1) collision avoidance queries against static meshes are O(n-squared) -- 8,000 meshes in a typical biome tile means 64 million pair checks per scatter operation, taking 45 seconds; (2) the height-sampling pass does 1 raycast per candidate foliage position to get the terrain height -- 10,000 candidates means 10,000 raycasts at 0.5ms each = 5 seconds; (3) the LOD group generation pass iterates every placed instance against every other instance to calculate clustering for LOD transitions -- another O(n-squared) at 10,000 instances = 12 seconds. Total: ~62 seconds per scatter. The target is under 5 seconds. Three optimisation approaches: (A) replace all three O(n-squared) passes with spatial hashing (build a uniform grid, query only neighbouring cells) -- reduces collision to O(n), LOD clustering to O(n), and brings total to roughly 6 seconds, but the spatial hash grid resolution must be tuned per biome (dense forest vs sparse desert) and a wrong grid size causes missed collisions; (B) move the collision and LOD passes to GPU compute via Unreal's ComputeShader API -- massively parallel, total drops to under 2 seconds, but GPU compute in Python/Editor scripting requires a C++ plugin that takes 2 weeks to build and is fragile to engine updates; (C) keep the current algorithm but add early-exit culling: discard any candidate position within 2 metres of an already-placed instance before running collision and LOD checks -- reduces the effective n by ~60%, bringing total to roughly 15 seconds with zero architectural changes, but the 2-metre minimum spacing produces unnaturally uniform distribution. Choose one. Rule out one with a specific technical or visual failure. State the single metric you use to determine whether the optimised tool is production-ready (not "it's fast enough" -- the specific measurement and threshold).`
  },

  // 06270a45 -- Codex: "best answer is too obvious, clipping-pose ask adds no separation"
  // Fix: make all options genuinely competitive, add a harder constraint
  {
    prefix: '06270a45',
    text: `You are a Sr Character Modeler on a live-service looter shooter in Unreal Engine 5. The hero character shipped at 65,000 triangles with a locked 150-bone skeleton. The designer requests 4 cosmetic attachment slots: shoulders, chest plate, helmet visor, and backpack. Each has a 5,000-triangle budget. The character already uses all 150 bones. Three attachment approaches: (A) socket-parent each attachment to the nearest single bone -- zero additional bone cost but attachments are rigidly stuck to one bone; during a heavy melee swing where the clavicle rotates 50 degrees, the shoulder attachment separates from the character's deltoid surface by up to 4cm, exposing a visible gap between the attachment edge and the character mesh; (B) add 4 virtual bones (one per slot) driven by runtime dual-quaternion blending of the 2-3 nearest existing bones -- the attachment deforms smoothly with the body surface, but virtual bones are not part of the skeleton asset and cannot be exported to third-party tools, locking your cosmetic pipeline to a custom runtime solution that 2 engineers must maintain; (C) each attachment is a cloth-sim-driven soft body that drapes over the character mesh using Chaos Cloth -- deforms naturally and handles arbitrary poses, but each cloth attachment costs 0.3ms on PS5, and 4 slots at 1.2ms total exceeds the character's physics budget by 0.8ms, requiring either a physics budget increase (which affects all other characters) or aggressive cloth LOD that makes the drape pop at 15 metres. Choose one. Rule out one with a specific technical or production risk that makes it unsustainable at a 20-character roster. State which of the 4 attachment slots is hardest to implement with your chosen approach and the specific body pose that causes the worst visual artefact for that slot.`
  },

  // 8c37e57f -- Codex: "tests art-direction communication, answerable by non-game character artist"
  // Fix: replace with a game-specific modelling problem about LOD and cinematic close-up
  {
    prefix: '8c37e57f',
    text: `You are a Sr Character Modeler on a single-player narrative RPG in Unreal Engine 5. A key NPC has 45,000 triangles at LOD0 with a face built for gameplay distance (10+ metres). The cinematic team now needs this character for 6 dialogue close-up shots at 1-metre camera distance. At 1 metre, the LOD0 face reveals: flat nasolabial folds that look painted-on (the normal map detail that reads at 10m disappears into smooth geo at 1m), visible faceting on the ear helix (only 8 triangles per ear), and lip geometry that is too coarse for blend shape lip sync (the lower lip is 4 quads). Three approaches: (A) build a separate cinematic LOD with 80,000 triangles -- higher-density face with 4x the lip geometry, 3x the ear detail, and sculpted nasolabial folds as geometry -- produces cinematic-quality close-ups but the cinematic LOD must be weight-painted to the same skeleton, doubling your skinning work, and any future animation changes must be validated against both LODs; (B) keep the 45,000-triangle mesh and use per-shot corrective blend shapes (4 blend shapes per shot, 24 total) that inflate the geometry in the camera-facing areas only -- no additional LOD to maintain but 24 extra blend shapes add 12MB to the character's memory footprint and each shot requires manual blend shape authoring; (C) keep the 45,000-triangle mesh and rely on post-process depth-of-field, cinematic lighting, and camera angle to hide the geometric limitations -- zero additional work but the director may reject shots where the face is in sharp focus at 1 metre. Choose one. Rule out one with a specific production or quality failure. State the minimum triangle density per square centimetre on the lip surface required for blend shape lip sync to read without faceting at 1-metre camera distance.`
  },

  // bd63615e -- Codex: "required minimum triangle count is arbitrary without camera/shader/animation test"
  // Fix: remove the arbitrary number ask, replace with a concrete validation method
  {
    prefix: 'bd63615e',
    text: `You are a Sr Character Modeler on a stylised multiplayer game targeting Switch and PS5. A hero character is 3 days from final approval at 35,000 triangles. The hands (800 tris per hand, 1,600 total) collapse into a mitten shape at the 8-metre default camera distance -- individual fingers are unreadable. Adding proper finger separation requires 2,400 tris per hand (4,800 total), pushing the character to 38,200 against the 35,000 budget. You are 3,200 tris over. Three approaches: (A) redistribute from the torso: the ornate chest armour (12,000 tris) can be simplified to 8,800 tris by converting the smallest filigree details to normal map -- frees 3,200 tris for the hands, but the armour is the character's primary visual identity and the filigree is visible in the character select screen at 3-metre camera distance; (B) keep the hands at 800 tris but add a visual mitigation: contrasting fingertip colour (dark nail polish on pale skin) that breaks up the mitten silhouette through colour, not geometry -- zero triangle cost and no other mesh changes, but the colour trick fails when the character equips gloves (6 of 15 cosmetic hand items are gloves); (C) exceed the budget to 38,200 tris and request a per-character exception from the tech art team -- fixes the hands without sacrificing anything but the exception must be justified. The tech artist asks: "Which 8 seconds of gameplay are the hands visible and important enough to warrant 3,200 extra tris on Switch?" You must name the specific gameplay action and camera state. Choose one. Rule out one and state the specific scenario where it fails. For option C, answer the tech artist's question: name the gameplay moment, the camera distance, and why finger readability matters for gameplay clarity in that moment.`
  },

  // 08ad45fd -- Codex: "shipped-game reference and universal ms threshold are rehearsable"
  // Fix: remove the reference/threshold asks, replace with a concrete implementation decision
  {
    prefix: '08ad45fd',
    text: `You are a Sr VFX Artist on a hack-and-slash action game in Unreal Engine 5 running at 60fps. Your three-hit sword combo VFX uses animation notifies to trigger hit-flash and sparks. The sound designer authored audio that peaks 3 frames (50ms) after the notify fires -- their reference was mocap video timing, not in-engine timing. At 60fps the 50ms desync is barely perceptible. At 30fps on last-gen consoles, the desync doubles to 100ms (3 frames at 33ms/frame) -- the visual hit-flash arrives visibly before the audio crack and players report it feels "broken." You cannot change the animation timing or the audio authoring. Three VFX-side fixes: (A) delay your hit-flash by 2 frames at 30fps and 1 frame at 60fps using a framerate-conditional branch in the Niagara emitter -- aligns both platforms but adds per-emitter framerate logic that must be replicated for every future melee VFX in the game (estimated 40+ emitters), creating a maintenance burden; (B) decouple the VFX entirely from the anim notify and trigger it from the damage system's hit-confirm callback instead -- architecturally clean and framerate-independent, but the hit-confirm fires 2-4 frames after the notify depending on network latency, so the VFX consistently lags the animation's visual impact moment by up to 66ms; (C) keep the VFX on the anim notify with no delay and accept the 100ms desync at 30fps -- the visual leads the audio, which research suggests is less noticeable than audio leading visual, and the 30fps audience is less sensitive to timing precision. Choose one. Rule out one with a specific player-experience consequence. State whether you apply your fix retroactively to the 12 existing melee VFX in the game or only to new VFX going forward, and the production cost of each choice in person-days.`
  },

  // 0ae6e3da -- Codex: "generic cross-platform UI, not game-specific"
  // Fix: make the scenario game-specific with HUD/gameplay UI constraints
  {
    prefix: '0ae6e3da',
    text: `You are UI/UX Lead on a free-to-play competitive arena game shipping on PC, PS5, and mobile. The post-match scoreboard displays: 10 player names, K/D/A stats, damage dealt, objective score, MVP indicator, and a "Play Again" button. The scoreboard must appear within 0.5 seconds of match end. On mobile (375px width), the 10-player table with 5 stat columns does not fit -- at 14px minimum font size, each row requires 420px minimum width. Three layout solutions for mobile: (A) horizontal scroll on the stat columns -- all data is accessible but the player must swipe to see damage and objective score, which are the two stats that differentiate a "good loss" from a bad one in your competitive community; (B) collapsible rows: show only player name and K/D by default, tap to expand for full stats -- fits in 375px but requires 10 taps to compare all players, and competitive players want to scan the entire lobby's performance at a glance; (C) switch to a card-based layout on mobile: each player gets a vertical card showing all stats, displayed in a swipeable carousel -- each card is fully readable but the player can only see one opponent at a time, losing the comparative table view that reveals match dynamics (e.g. "our tank out-damaged their carry"). Choose one. Rule out one with a specific competitive-community consequence. State which single stat column you would cut entirely from the mobile view if none of the three layouts tested well in playtesting, and the gameplay reason that stat is least valuable on a post-match screen.`
  },

  // b545f5f5 -- Codex: "core problem could appear in any multi-platform product, game-specific stakes thin"
  // Fix: make it about in-game UI consistency across gameplay states, not general design systems
  {
    prefix: 'b545f5f5',
    text: `You are UI/UX Lead on a competitive game in Unreal Engine 5 using UMG. The game has three distinct UI contexts that share the same visual language but operate under different performance constraints: (A) the in-match HUD (rendered every frame at 60fps, maximum 0.5ms GPU budget for all UI, limited to 20 draw calls); (B) the between-match menu (full-screen, rendered at 30fps during loading, no GPU budget constraint, full animation and transparency allowed); (C) the in-match tactical overlay (toggled by holding a button, renders on top of the 3D world at 60fps, must not obscure more than 30% of the screen). The art director approved animated button transitions (150ms ease-in-out with glow) for the between-match menu. The same button style appears in the tactical overlay, but the 150ms animation causes a perceptible input delay when toggling tactical options during combat -- players press a button, see no immediate response for 150ms, and press again (double-input). Three solutions: (A) use the animated button everywhere for visual consistency -- accept the double-input problem in the tactical overlay as a training cost that players will learn; (B) use instant-response buttons (0ms transition, immediate state change) in the tactical overlay and animated buttons in the menu -- solves the input problem but the same button looks and feels different in two contexts, which QA will file as a visual bug; (C) reduce the tactical overlay button animation to 50ms (below perceptual threshold for input delay) with no glow effect -- a middle ground but the art director may reject buttons that "feel different" from the menu even if they look similar. Choose one. Rule out one with a specific gameplay or visual-consistency failure. State the maximum animation duration in milliseconds you would allow on any interactive element that appears during active gameplay, and the input-response research that justifies that threshold.`
  },

  // 105a4a83 -- Codex: "aesthetic preference and general readability, not game-specific"
  // Fix: tie the UI redesign to specific game mechanics and player information needs
  {
    prefix: '105a4a83',
    text: `You are UI/UX Lead on a dark fantasy action RPG in Unreal Engine 5 using UMG. The game's core loop involves reading enemy attack telegraphs (0.5-1.2 second wind-up animations) and dodging. The current placeholder HUD has: a health bar, stamina bar, 4 ability cooldowns, an equipment wheel, and a compass. The art director wants the HUD to match the game's hand-painted medieval aesthetic. Three specific HUD problems to solve: (A) the health bar: the placeholder is a horizontal red bar. The art director wants an ornate golden frame with a liquid-fill animation. But the liquid-fill animation takes 300ms to settle -- during a boss fight where a single hit can remove 40% HP, the player cannot read their remaining health for 300ms after getting hit, which is 25-60% of the next attack telegraph window; (B) the stamina bar: the art director wants it rendered as chain links that break as stamina depletes. Each link represents 20% stamina. At 60% stamina (3 links remaining), the player cannot distinguish "I have one dodge left" from "I have two dodges left" because the visual difference between 2 and 3 intact links is too subtle at 1080p couch distance; (C) the ability cooldowns: the placeholder uses numeric countdown timers (e.g. "3.2s"). The art director wants radial clock-wipe icons with no numbers. But the game has abilities with 3-second, 5-second, and 8-second cooldowns, and without numbers, players cannot plan ability rotations during the 1.2-second windows between enemy attacks. Choose two of the three to redesign to the art director's vision. State which one you keep as a functional (non-thematic) element and the specific gameplay-timing reason it cannot be made decorative. For the two you redesign, state one constraint you add to the art direction to preserve gameplay readability.`
  },
];

(async () => {
  let applied = 0;
  let notFound = 0;
  for (const r of REWRITES) {
    const result = await pool.query(
      "UPDATE interview_question_bank SET question_text = $1, updated_at = NOW() WHERE id::text LIKE $2 RETURNING id",
      [r.text, r.prefix + '%']
    );
    if (result.rows.length) {
      console.log('APPLIED:', result.rows[0].id);
      applied++;
    } else {
      console.log('NOT FOUND:', r.prefix);
      notFound++;
    }
  }
  console.log('\nTotal applied:', applied, 'of', REWRITES.length);
  console.log('Not found:', notFound);
  await pool.end();
})();
