require('dotenv').config();
const { Pool } = require('pg');
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const REWRITES = [
  {
    // 38ec32f8 - score 6, "too thin on constraints, generic coordination language"
    prefix: '38ec32f8',
    text: `A VFX artist has built a 3-second ability effect for a ranged character's projectile in a 5v5 multiplayer hero shooter on PS5, Xbox, and PC. The animation is 2.8 seconds with a release frame at 0.9 seconds. The gameplay damage event fires server-side at 1.2 seconds. The VFX trail particle starts at 0.85 seconds and the impact burst is at 2.4 seconds. You need audio to sync to all four systems, but on a 150ms-latency multiplayer connection the server damage confirmation arrives after the local prediction has already played your impact sound. The character also has a voice line ("Fire!") that the narrative director wants at the release frame, but the combat designer says it clutters readability in team fights with 5+ abilities firing per second -- and your audio profiler shows the voice bus hitting its 8-voice limit during these peaks, meaning the voice line would steal a slot from enemy ability wind-up callouts that players need for survival. The console voice budget for this character is 24 simultaneous voices total across all their abilities, movement, and UI feedback. Walk us through: which system becomes the sync master for the audio timing, how you handle the 150ms network-latency mismatch between local prediction and server confirmation (specifically: do you play a speculative impact sound on client prediction and then play a second confirmation sound, or do you wait for server confirmation and accept the latency), what you do with the voice line given the 8-voice limit on the voice bus during peak combat, and what specific voice priority settings you set so this character's 24-voice budget degrades gracefully when 3 of the same character are on a team.`
  },
  {
    // 428ec7e5 - score 6, "no concrete project constraints to separate seasoned lead from competent producer"
    prefix: '428ec7e5',
    text: `You are briefing two external partners simultaneously for a multiplayer arena game with 8 playable characters shipping in 9 months on PS5, Xbox, and PC. Partner A is a composer delivering an adaptive music system with exploration, combat-ramp, and victory/defeat states across 4 biome-themed maps. Partner B is an outsource house delivering 240 combat sound effects -- 30 per character covering abilities, hits, movement, and UI feedback -- to a 6-week deadline with two review gates. Your internal team is two sound designers who will integrate everything in Wwise. Here is the constraint that makes this hard: the composer needs stems that slot into your horizontal re-sequencing system, which requires specific bar lengths (4-bar segments at 120 BPM), stem naming that matches your Wwise Music Segment hierarchy, and delivery in 48kHz 24-bit WAV -- but the composer's previous work was all linear and they have never delivered stems for interactive music. The outsource house has never worked with game middleware and will deliver raw WAVs -- but 30 sounds per character must each have 3 round-robin variants at specific loudness targets (-18 LUFS per variant) to match your in-game mix, and the naming must follow your event convention (Character_Ability_Layer_Variant) or your two-person team will spend weeks renaming files. The outsource house's first delivery of 60 sounds on a previous project came back at wildly inconsistent loudness (-12 to -24 LUFS) with no naming convention. What specific technical specification do you put in each brief that prevents the failures you have seen before, what acceptance criteria do you set at each review gate with measurable pass/fail thresholds, and what is your plan when the composer's first milestone delivery arrives in 4-bar segments that are 125 BPM instead of 120 because they composed at a different tempo?`
  },
  {
    // 9746f4b5 - score 4, "under-specified, invites generic scope-negotiation"
    prefix: '9746f4b5',
    text: `The game director wants every character in a 16-character hero roster to have a unique audio identity: distinct footsteps on 5 surface types (60 variations per character after round-robin), 8 ability sounds each with 3 layers, hit reactions per damage type (blunt, slash, projectile, elemental -- 4 variants each), and 40 voice lines per character. That is roughly 2,800 individual sound events across the roster. Your team is two sound designers and one external outsource partner. You have 14 weeks before content-lock and a 256MB audio memory budget on console. The outsource partner can deliver 40 sounds per week at your quality bar. Your two internal designers can each produce 25 sounds per week while also handling integration. That is 90 sounds per week total, meaning 2,800 events would take 31 weeks -- more than double your timeline. The game director will not accept shared footstep sets across characters even for characters of similar weight class. Here is your forced decision: you cannot ship all 2,800 events at full quality. The pick rates from the beta show the top 4 characters account for 68% of all play time. The bottom 4 characters have a combined 8% pick rate. Do you: (A) ship 8 characters at full quality and 8 at a reduced set (footsteps only, shared hit reactions, 20 voice lines instead of 40) -- and if so, which 8 get full treatment; (B) ship all 16 at a reduced set with a plan to backfill post-launch; or (C) push back on the unique-footstep requirement with player perception data showing that in blind tests players cannot distinguish character footsteps during combat? For whichever option you choose, explain how you allocate work between internal team and outsource, what the memory budget breakdown per character is, and what you say to the game director when they ask why their bottom-4 characters sound worse.`
  },
  {
    // c522f74b - score 5, "no map type, combat density, bus behaviour, or measurable mix constraint"
    prefix: 'c522f74b',
    text: `A level designer has built an underground cavern map for a 5v5 hero shooter. The ambient soundscape uses 14 emitters (dripping water echoes, distant rumbles, creature stirring, wind through crevices) and sits at -18 LUFS on the ambient bus during exploration. During 5v5 team fights in the cavern's central chamber -- a 20-metre-diameter space with hard stone surfaces and a 4-second reverb tail -- ability sounds, hit impacts, and voice callouts push the master bus from -18 LUFS to -8 LUFS within 500ms. The compressor on the master bus (ratio 4:1, threshold -14 LUFS, attack 10ms, release 100ms) is pumping audibly, and the reverb tail is smearing combat audio so players cannot distinguish individual ability wind-ups. The Wwise profiler shows 48 simultaneous voices during peak combat with the master bus limiter engaged 90% of the time. The level designer says the atmosphere is the entire identity of the map and refuses to reduce emitter count -- the cavern was chosen as the ranked-mode featured map specifically because of its audio identity. The combat designer says players are reporting they cannot hear enemy ability wind-ups, which in ranked play means dying to abilities they should have dodged. Your bus hierarchy is Master > Music / SFX / Voice / Ambient with no sub-grouping within SFX. You have the Wwise session open. Walk through: what sub-buses you create within SFX and what voice limits you set on each, what sidechain ducking you apply from combat audio to the ambient bus (specify the duck volume, attack, release, and recovery curve), how you shorten the reverb tail during combat without the transition being audible (do you automate the reverb decay via RTPC or switch to a dry aux send), and how you verify with the level designer that the atmospheric identity survives by A/B-ing exploration-only versus combat states.`
  },
  {
    // 07369ded - score 5, "no production constraints, map scale, player-count demands, or hard trade-offs"
    prefix: '07369ded',
    text: `You are designing audio for a 5v5 multiplayer map set in a war-torn coastal city. The map has four zones: an open harbour (crashing waves, seagulls, distant foghorn), a narrow market street with overhanging awnings and hard parallel walls creating strong early reflections, an underground sewer connecting two capture points with a 3-second reverb tail and constant water flow, and a rooftop area exposed to wind with distant artillery every 20-40 seconds. The game runs on PS5, Xbox, and PC with a 48MB audio memory budget for this map's soundbank. At peak combat density, 10 players fire abilities simultaneously producing 30+ sound events per second. The console voice limit is 64, and each zone's ambient soundscape uses 8-12 voices just for environmental audio. Your specific design challenge: the sewer's water flow masks enemy footsteps, which the game designer considers a feature ("audio stealth zone"), but competitive players in the beta complained it is unfair because the footstep masking is inconsistent -- it depends on where the listener stands relative to the water flow emitters, and one position near capture point B has a dead spot where footsteps are audible at 15 metres while everywhere else they are masked at 5 metres. You need to decide: do you make the sewer's footstep masking consistent (all masked below 8 metres) which removes the dead spot but also removes a skill-expression element, or do you keep the dead spot and tune it to be predictable so competitive players can learn it? Walk through your design for all four zones' ambient soundscapes, your reverb zone transition strategy at boundaries (specifically: what happens when a player stands on the sewer entrance stairs hearing both harbour and sewer acoustics), and your decision on the footstep masking with the gameplay reasoning behind it.`
  },
  {
    // 07a28ba7 - score 4, "no target platform, mix problem, reference format, or verification requirement"
    prefix: '07a28ba7',
    text: `You are ending a 3-month mentorship with a 4-person audio team building an online co-op shooter on Unreal with Wwise. Their mix has three problems they do not recognise: the master bus loudness varies by 8 LU between maps (the desert map is -14 LUFS, the forest map is -22 LUFS), their weapon tails are 6dB louder than the reference games in the genre (Call of Duty at -18 LUFS per gunshot tail versus theirs at -12 LUFS), and their UI sounds are mixed so quietly that playtesters report missing notification pings during combat (UI bus is at -36 LUFS, should be -24 LUFS for audibility). The team monitors on KRK Rokit 5s in an untreated room and tests only on PC -- they have never listened on PS5 through TV speakers or on a gaming headset. You need to build a reference mix document they can use after you leave. Walk through: what loudness targets you set per bus (master, music, SFX subdivisions, voice, UI, ambient) and what standard you reference (EBU R128, platform TRC guidelines, or genre convention -- and why), how many reference clips you include in the document and what they demonstrate (provide 3 specific examples: one showing correct weapon loudness relative to footsteps, one showing map-to-map loudness consistency, one showing UI audibility during combat), what format you deliver the document in so it is usable in daily work (not a PDF that gets filed and forgotten), and what verification checklist of 5 specific measurements the team runs when they add a new map or weapon class -- with pass/fail thresholds for each measurement.`
  },
  {
    // 23ce65d0 - score 6, "needs concrete content volume, staffing, platform, or regression constraints"
    prefix: '23ce65d0',
    text: `You are Audio Lead on a free-to-play multiplayer game on PS5, Xbox, and PC that ships a new character every 6 weeks and a new map every 12 weeks. Each character requires 45 sound events (8 abilities with 3 layers each, 5 surface footstep types with 4 round-robin variants, 12 voice lines, UI feedback). Each map requires a new ambient soundscape, reverb zones, and 10-15 environmental emitters. Your team is three sound designers. The console soundbank budget is 384MB total and you are at 310MB after 12 characters and 6 maps -- meaning you have 74MB for the next content, but each character averages 6MB and each map averages 8MB. At current growth rate you hit the budget ceiling at character 20 (8 characters from now, roughly 48 weeks). Your Wwise project has 1,800 events and naming discipline has drifted -- the last two characters used different naming conventions from the first ten. The live-service cadence means you cannot pause content delivery to refactor. You have a character shipping in 3 weeks and a map shipping in 6 weeks, both being built now. Walk through: what template system you build so character 13 is systematic rather than heroic (what the Wwise work unit template contains, what the naming convention enforces, what the review gate catches before events go into the main project), how you handle the growing memory pressure without retroactively reworking shipped content (what compression, streaming, and bank-loading strategy you implement for new content that buys you runway), what breaks first if you lose one designer mid-season (which deliverables slip and what you cut from the character's audio to ship on time with two designers), and at what point you escalate to the producer that the content cadence is unsustainable with current team size -- what data you present.`
  },
  {
    // 58ae594b - score 6, "inherited system and milestone risk not specified enough"
    prefix: '58ae594b',
    text: `You inherit a multiplayer PvP game 8 months into development on Unreal with Wwise, targeting PS5, Xbox, and PC. All audio was implemented by a gameplay programmer with no audio background. The Wwise project has 400 events with no naming convention (some use CamelCase, some underscores, character names are inconsistent), everything is loaded into a single soundbank (currently 180MB, budget is 256MB), there are no bus groups -- all sounds route directly to the master bus with no sub-mixing, and half the events use 96kHz source files that were never converted (48kHz is your target). Reverb is handled by a single global aux bus at a fixed 2.5-second decay rather than per-zone sends. The next milestone is in four weeks: a vertical slice demo for the publisher on a base PS5. The demo map is the only map with all gameplay systems active -- 10 characters, destructible objects, and a boss encounter. The publisher's audio director will be in the room. Here is the sequencing problem: converting the 96kHz files to 48kHz and re-encoding would save approximately 80MB (bringing you to 100MB) and dramatically improve load times, but touching those files risks breaking the 400 event references in Blueprints if the Wwise IDs change during reimport. The programmer who set up the integration used hard-coded event name strings in 200+ Blueprints rather than Wwise event references. What do you fix in the first week that has the highest demo impact (bus structure, reverb, or file conversion), what is the specific risk if you touch the 96kHz files and how do you mitigate it, what does the demo sound like after your 4-week triage versus what it would sound like with 3 months of proper work, and what do you tell the publisher's audio director about the state of the audio when they ask?`
  },
  {
    // 5cb2485c - score 6, "broad, candidate can recite middleware concepts without resolving a constraint"
    prefix: '5cb2485c',
    text: `You are implementing a dynamic music system in Wwise for a 5v5 hero-based multiplayer game with 4-minute rounds on 6 maps. The system handles five states: pre-round lobby (15 seconds), exploration/positioning (30-60 seconds of setup phase), combat escalation (triggered when 3+ players are within 15 metres of each other), victory sting, and defeat sting. Each map has a unique biome theme with 12 stems from the composer: 4 melodic layers, 4 rhythmic layers, and 4 textural layers. Rounds can swing from full 5v5 combat to a single survivor hiding in under 2 seconds -- and this happens multiple times per round. The music must transition between states within 500ms to feel responsive but cannot produce audible cut artifacts. Here is the specific implementation problem: during a playtest, the music whiplashed between combat and exploration 6 times in 10 seconds because players were dancing around the 15-metre engagement threshold. The combat-to-exploration transition uses a 500ms crossfade, which at 6 transitions per 10 seconds creates a constant wash of overlapping stems that sounds like mush. Additionally, when a player dies and enters spectator mode watching a teammate in a different map zone, the music system receives conflicting state inputs -- the dead player's zone says "exploration" but the spectated player's zone says "combat." Walk through: what hysteresis or cooldown you add to the combat trigger so the whiplash stops (specify the timing), how you handle the spectator state conflict (which player's context drives the music), what Wwise container structure you use (switch containers versus music segments versus playlists, and why), and what the transition sounds like from full combat to single-survivor stealth -- specifically which stems drop first, which sustain, and over what duration.`
  },
  {
    // 95c12b0b - score 4, "no constraints, artefact expectations, participant mix, or specific mix failure"
    prefix: '95c12b0b',
    text: `You are running a 90-minute mix clinic for a 5-person audio team (2 sound designers, 1 composer, 1 audio programmer, 1 junior who joined 3 weeks ago) on a co-op PvE shooter built in Unreal with Wwise, targeting PS5 and PC. The build has three mix problems: (1) weapon fire masks enemy audio tells -- specifically, the player's assault rifle at -10 LUFS per shot masks the enemy heavy unit's 0.8-second charge-up growl at -16 LUFS, which is the only warning before a one-hit-kill attack; (2) the adaptive music overwhelms voice comms during boss encounters -- the boss music's percussion bus hits -8 LUFS while player voice chat sits at -14 LUFS, and the music has no sidechain ducking to voice; (3) there is a 4dB loudness jump when transitioning between the hub world (-20 LUFS integrated) and mission levels (-16 LUFS integrated) because the hub was mixed by the junior and the missions were mixed by the senior designer. You have the Wwise session, the game running on a PS5 devkit, and studio monitors. Walk through how you structure the 90 minutes: what do you listen to first and why (the specific in-game scenario, not "we listen to the mix"), how do you use the Wwise profiler to make the weapon-masking problem visible to the junior (what specific meter reading, bus level, or voice-stealing event do you point at), what sidechain ducking parameters you demonstrate for the boss music issue (duck volume in dB, attack, release, recovery, and which bus drives the sidechain), what the action items are at the end with specific owners and deadlines for each, and how you prevent the hub/mission loudness mismatch from recurring (what process or automated check you introduce).`
  },
  {
    // 9c1cd40b - score 5, "'muddy mix' without source symptoms, player count, bus structure, or profiler evidence"
    prefix: '9c1cd40b',
    text: `You are mentoring a 3-person audio team on a 30v30 multiplayer battle game built in Unreal with FMOD. Their combat mix collapses during large engagements: the master bus hits -3 LUFS, the limiter is constantly engaged, players report they cannot distinguish their own weapon fire from teammates', and spatial audio flattens so everything sounds like it is coming from the same distance. The FMOD profiler shows 140+ simultaneous voices during peak combat (budget: 96), CPU on the audio thread hits 6ms (budget: 4ms), and the virtual voice system is not configured -- every sound plays regardless of audibility. The team's bus structure is Master > Music, Master > SFX, Master > Voice, with all combat sounds -- abilities, weapons, impacts, footsteps, environmental destruction -- on the single SFX bus. There are no voice limits on any bus. The SFX bus has a single compressor with a 2:1 ratio and -12dB threshold that does nothing useful at the current levels. Rather than rebuilding their hierarchy yourself, walk them through the diagnosis step by step: what FMOD profiler view you open first (the voice count graph or the bus level meters, and why that order), how you explain why a flat SFX bus causes this failure at 30v30 but worked at 5v5 (the specific numbers: 5v5 produces ~35 voices on SFX, well within 96; 30v30 produces 140+, exceeding it by 46%), what sub-bus structure you guide them to create (name the buses, the voice limits per bus, and the priority values -- e.g., Player_Weapons at priority 100 with a 6-voice limit, Teammate_Weapons at priority 60 with a 12-voice limit), how virtual voice behaviour should work for sounds that drop below audibility (-60dB threshold, send to virtual, resume on volume increase), and what the mix should sound like when working -- specifically which 5 sound categories the player should always hear at peak combat and which 3 categories are acceptable to lose.`
  },
  {
    // bf02a2f8 - score 4, "no specific spatial failure, test environment, player behaviour, or measurement"
    prefix: 'bf02a2f8',
    text: `You discover that the team's spatial audio implementation on a first-person co-op shooter (Unreal + Wwise, PS5 and PC) has two specific problems. Problem 1: the HRTF attenuation curves are linear instead of inverse-square, so sounds at 20 metres feel almost as loud as sounds at 5 metres -- the profiler shows a sound at 20m is only 6dB quieter than at 5m, when it should be approximately 12dB quieter for inverse-square. This means players cannot judge whether an enemy is in the next room (5m) or across the building (20m). Problem 2: the spread parameter is fixed at 100% for all emitters, meaning a point-source enemy footstep sounds identical in spatial width to an area-source waterfall. Footsteps should be tight point sources (spread 0-20%) so players can pinpoint direction, while ambient environmental sounds should be wide (spread 60-100%). The team tested on stereo desktop speakers in a noisy open-plan office and says it "sounds fine." Telemetry shows 70% of the player base uses headphones, where these problems are dramatically more apparent. The Audio Lead pushes back, saying the current settings have shipped in the beta and changing attenuation will require re-tuning every emitter in the game (400+ emitters across 6 maps). Walk through: what in-engine test scenario you build in 30 minutes to make the problem audible even on speakers (hint: place two identical emitters at 5m and 20m and toggle between them), what the correct attenuation curve shape and distance values should be for footsteps (max distance, curve type, near/far thresholds), gunfire (different max distance and falloff), and ambient loops (different spread and attenuation), how you scope the re-tuning work so it is not 400 emitters but a manageable batch (how many Wwise attenuation ShareSets do you actually need), and how you frame this to the Audio Lead so they see it as a parameter fix on 8-10 ShareSets rather than 400 individual emitter changes.`
  },
  {
    // c2bb46ed - score 6, "lacks timing windows, mix budget, animation hooks, or player readability targets"
    prefix: 'c2bb46ed',
    text: `You are designing the complete audio for a new heavy melee tank character in a 5v5 hero shooter. The character has: a ground-slam ultimate (1.2-second wind-up animation where the character leaps, 0.3-second impact, 1.5-second recovery; the slam deals damage in a 10-metre radius and the screen shakes for all players within 20 metres), a shield ability (0.4-second deploy, holds for up to 5 seconds, absorbs projectiles with per-hit impact sounds, 0.6-second retract), and passive armour sounds during movement (the character weighs 300kg and wears plate armour; footsteps must communicate weight class so enemies can identify this character by sound alone in a game with 20 characters). The character's voice budget is 16 simultaneous voices. The ground-slam ultimate is the key challenge: during the 1.2-second wind-up, you need a rising tension sound that communicates "get out of the area" to enemies (this is a gameplay-critical audio tell that the game designer requires), the 0.3-second impact needs to feel like the heaviest hit in the game (the current heaviest is a hammer strike at -8 LUFS peak with 3 frames of hit-stop), and during the 1.5-second recovery the residual rumble must not mask teammate voice callouts. All of this must work when two tank characters slam simultaneously in a team fight. Walk through your layering for each ability phase with specific timing relative to animation frames, what your loudness targets are per element (wind-up, impact, rumble), how you ensure the wind-up audio tell is audible and directional from 20 metres even during combat (what frequency range, what HRTF behaviour), and how two simultaneous slams sound distinct rather than becoming a wall of noise -- what priority and ducking rules you set.`
  },
  {
    // ea04207e - score 5, "too open-ended, rewards opinionated theorising"
    prefix: 'ea04207e',
    text: `You have shipped two games using Wwise and are now on a project using FMOD. In your most recent Wwise title -- a 5v5 multiplayer shooter with 16 characters and 8 maps -- you hit a specific limitation: Wwise's Music Segment system could not handle the rapid state changes your game required. During 5v5 team fights, the music system received 3-5 state change requests per second (combat/stealth/combat/stealth as players moved in and out of engagement range), and the Music Segment transitions could not queue or cancel mid-transition. The result was a 200ms audio gap every time two transitions overlapped, which happened constantly during competitive play. Your workaround was to bypass the Music Segment system entirely and drive stems via standard Switch Containers with manual crossfades in code -- which cost your audio programmer 3 weeks of implementation and lost you access to Wwise's Music playlist features, interactive cues, and MIDI integration for the rest of the project. The architectural constraint that makes this hard for Audiokinetic to fix: the Music Segment system processes transitions on a separate thread from the main audio engine, and allowing mid-transition cancellation would require thread synchronisation that could introduce audio glitches on consoles with tight audio thread budgets. Now that you are on FMOD: does FMOD's Event-based music system handle this case better, and if so, why architecturally? If not, what workaround do you implement, and how does it differ from the Wwise workaround given FMOD's different threading model?`
  },
  {
    // 2b583753 - score 5, "no onboarding timeline, project risk, expected artefacts"
    prefix: '2b583753',
    text: `You are onboarding a mid-level sound designer onto a multiplayer game 14 months into development. The Wwise project has 2,200 events across 16 characters and 8 maps, a strict naming convention (Character_Ability_Layer_Variant), a bus hierarchy with 6 sub-mix groups (Player_Weapons, Team_Weapons, Enemy_Weapons, Abilities, Environment, UI), and a soundbank strategy that loads per-character and per-map. The new hire starts Monday. Your next milestone is in 5 weeks and requires audio for 2 new characters (90 events total). The risk: the new hire creates events that break naming conventions, routes sounds to wrong buses, or bloats soundbanks by not following the compression settings (Vorbis quality 4 for all combat SFX, PCM for UI). Their first task determines whether they can contribute to the milestone or require 3 weeks of correction. Walk through: what documentation you prepare before they arrive (not a wiki page -- what specific Wwise project walkthrough, what annotated event examples, what "here is a correctly set up character" template), what their first task is and why (not "familiarise yourself" -- a specific deliverable: create 4 footstep variants for an existing character on a new surface type, following the template, with correct naming, bus routing, and compression), what review gate you put on their work before it enters the main project (do they commit to a branch, do you pair-review in Wwise, or do they export a SoundBank and you verify the binary size), and at what milestone (2 weeks? 4 weeks? after the first character ships?) you trust them to commit directly without your review.`
  },
  {
    // 494a483d - score 5, "lacks concrete player impact, schedule data, or acceptance criteria"
    prefix: '494a483d',
    text: `You shipped a multiplayer game 3 months ago. During a post-launch analytics review, you discover that 14 ability sounds across 4 characters are still using placeholder assets from pre-alpha -- mono recordings at 22kHz (your standard is stereo 48kHz), no round-robin variation (your standard is 4 variants minimum), no spatial audio setup (all play as 2D), and loudness levels 8dB below your mix target. QA never flagged them because they functioned. Players have not complained because the 4 characters have a combined 8% pick rate. The game designer considers them "good enough." The producer says the live team's bandwidth for the next 8 weeks is fully allocated to Season 2's new character audio (1 character per 6 weeks). Replacing all 14 sounds properly takes one designer 6 days. Here is the forced decision: Season 2 launches in 5 weeks with a new character that has a marketing trailer featuring their abilities. If you pull a designer for 6 days to fix the placeholders, the new character ships with only 3 round-robin variants per ability instead of 4, and the community will notice the reduced variation on the featured character immediately. If you leave the placeholders: the 4 affected characters are getting a balance patch in Season 2 that will increase their pick rates by an estimated 15-25% based on the designer's projections, meaning more players will hear the placeholder audio. Which do you fix and why? Walk through your decision criteria: at what pick rate does placeholder audio become unacceptable, what is the minimum acceptable quality you can ship (is mono at 22kHz ever acceptable or is it always a fix-now), and what process change do you implement so placeholders cannot silently ship again -- specifically, what metadata tag or Wwise convention flags an event as "placeholder" and what build-time check catches it?`
  },
  {
    // 5cd7efb9 - score 5, "does not force examples tied to a specific game, asset class, or production workflow"
    prefix: '5cd7efb9',
    text: `You are building the audio style guide for a new dark fantasy co-op game with a tone between Diablo 4 and Monster Hunter World. The game has melee combat (swords, hammers, spears), ranged magic (fire, ice, lightning, necrotic), creature encounters (12 creature types from wolves to a 30-metre dragon boss), and environmental hazards (poison swamps, collapsing structures, lava flows). Your team is two sound designers plus an outsource partner who will handle creature audio. The outsource partner has shipped three sci-fi shooters but never fantasy -- their instinct will be to reach for synthesised, processed sounds when your game needs organic, recorded-source material. Here is the specific problem the style guide must solve: on the last project with this outsource partner, they delivered creature vocalizations that sounded like filtered white noise with pitch modulation -- technically functional but sonically indistinguishable from each other. Your game's 12 creatures must each be identifiable by sound alone in the dark (a core gameplay mechanic -- players use audio to identify threats before visual contact). The style guide must give the outsource partner enough creative direction that their wolf sounds nothing like their spider, their spider sounds nothing like their wraith, and none of them sound like sci-fi aliens. Walk through: what 3 reference recordings or games you cite for tone and why each (one for creature vocals, one for weapon impacts, one for environmental atmosphere), how you define the sonic palette for creature audio specifically (what source material is in-bounds -- animal recordings, foley, acoustic instruments -- versus what is out-of-bounds -- granular synthesis, heavily processed electronic elements), how many example assets you include per creature type (and what they demonstrate: a "this is correct" example plus a "this is wrong" example for at least 2 creature types), and what the outsource partner's acceptance test is for their first delivery of 3 creatures -- what do you listen for, what measurements do you take, and what fails the review.`
  },
  {
    // afd57286 - score 5, "relevant pipeline topic but too unconstrained, generic checklist"
    prefix: 'afd57286',
    text: `You are establishing the audio pipeline from scratch for a studio of 4 sound designers building a cross-platform (PC, PS5, Xbox Series X) multiplayer game in Unreal Engine 5 with Wwise. The codebase is in Perforce with a 10GB depot. The Wwise project generates .bnk files that are 200MB+ and binary. Source audio files (WAVs, Pro Tools sessions) total 40GB and growing at approximately 5GB per month. Your programmers want all game-facing assets in Perforce but do not want the Wwise authoring project or source WAVs in the main depot because it slows sync from 4 minutes to 25 minutes. Here is the pipeline problem you must solve: two designers edited the same Wwise work unit (Character_Weapons) simultaneously last week. Wwise work units are XML files that Perforce treats as binary by default. The merge produced a corrupted .wwu file that took 4 hours to reconstruct manually, during which no one could generate soundbanks. This will happen again -- your 4 designers all touch character audio daily. Walk through your pipeline: where source audio lives versus Wwise project files versus generated soundbanks (separate depot? same depot with workspace views? Git LFS for audio?), how you prevent Wwise work unit merge conflicts (what Perforce file type settings, what Wwise project organisation into work units that minimise shared editing, what checkout-lock policy), what your file naming convention is and how you enforce it (manual review at PR or automated pre-submit validation script -- and what the script checks), what platform-specific conversion settings you use for PS5 versus Xbox versus PC (codec, sample rate, quality level -- with the reasoning for each choice), and what breaks first when the team scales from 4 to 8 designers -- specifically, which part of this pipeline does not scale and what you would change.`
  },
  {
    // 17b222a5 - score 4, "no concrete spatial setup, player task, failure mode, or measurement"
    prefix: '17b222a5',
    text: `You are teaching a junior sound designer the difference between spatial audio that is technically functional and spatial audio that serves gameplay. The game is a 4-player co-op extraction shooter where players must locate AI enemies by sound before visual contact -- the game designer considers this the core tension mechanic. The current Wwise implementation uses default 3D spatialisation with a linear attenuation curve from 0 to 50 metres, no occlusion, and the same HRTF profile for all sound types. Technically, sounds pan correctly and attenuate with distance. However, playtest data shows players can only identify enemy direction 40% of the time (target: 80%) and cannot distinguish whether an enemy is one floor above or on the same level. The junior's task is to fix this. You set up a teaching exercise: a test level with a single enemy type that has 3 sound events (footsteps at -22 LUFS, weapon cock at -18 LUFS, growl at -16 LUFS). The enemy spawns at 5 fixed positions: 10m ahead on the same floor, 10m behind on the same floor, 10m directly above, 10m ahead through a wall, and 10m ahead through an open doorway. Walk through: what attenuation curve shape and distance values you teach the junior to set for each sound type (and why enemy footsteps need a steeper near-field curve than ambient sounds), how you implement occlusion so sounds through walls are filtered differently from sounds through open doorways (what Wwise obstruction/occlusion values, what frequency filtering, what the player should hear differently), how you address the vertical localisation problem (what elevation panning or HRTF adjustment distinguishes "above" from "same level"), and what the pass/fail test is -- you have the junior play the test level 20 times blindfolded and record their directional accuracy; what percentage demonstrates they have implemented the spatial audio correctly?`
  },
  {
    // 260dcca4 - score 5, "too broad and not constrained enough"
    prefix: '260dcca4',
    text: `You are dropped into an active 5v5 multiplayer shooter project on day one of a 3-month mentorship. The game is built in Unreal with FMOD, has 10 characters, 4 maps, and is 16 months into development. The team is 3 sound designers, none with more than 2 years of game audio experience. The producer tells you the mix "falls apart" during team fights, players complain they cannot hear footsteps, and the last two characters shipped with audio that "does not match the others." You have the FMOD Studio project, a PS5 devkit, and the game running. Your first-week audit must produce a prioritised findings document. Here is what you discover in your first 4 hours: the FMOD profiler shows peak voice count hitting 88 during team fights (budget: 64, meaning 24 sounds are being stolen), the SFX bus has no sub-grouping so there are no voice limits per category, the last 2 characters' ability sounds are 4dB louder than the first 8 characters' because the designer who made them used different monitoring levels, and footsteps are categorised as "ambient" priority (lowest) so they are the first sounds stolen during combat -- which is why players cannot hear them. Walk through your first-week audit: what do you listen to first (which of the 4 maps, why, and what specific in-game scenario), what FMOD profiler metrics you capture to quantify the mix collapse (list the 4 specific numbers you screenshot for the findings document), what A/B test you run between the old characters and the new 2 to identify the loudness inconsistency (what measurement, what tool), and what your findings document looks like -- its exact format (table? ranked list?), how many findings maximum (what do you defer to week 2), and how you rank priority (cert risk > gameplay impact > polish).`
  },
  {
    // 67fae9bb - score 6, "lets candidates recite compression concepts without solving a specific mix failure"
    prefix: '67fae9bb',
    text: `You are mixing a 5v5 hero shooter where a typical team fight produces 60+ simultaneous sound events. The dynamic range problem is specific: during exploration the ambient sits at -24 LUFS and a single footstep reads clearly at -20 LUFS, but within 500ms a team fight erupts and the SFX bus jumps to -10 LUFS, causing the master limiter (brick-wall at -1 dBTP) to engage and flatten the mix. The master limiter is reducing gain by 8dB during fights, which crushes spatial positioning and makes everything sound equidistant. Players on headphones report listening fatigue after 30-minute sessions. Your current bus hierarchy is Master > Music / SFX / Voice / Ambient, with no sub-grouping within SFX. You must restructure and mix this without changing the game's overall loudness target of -16 LUFS integrated on the master bus. Walk through your strategy: what sub-buses you create within SFX (name them with their voice limits), what compressor settings you place on the Player_Weapons sub-bus versus the Enemy_Weapons sub-bus (ratio, attack, release, threshold -- and why they differ: your own weapons need punch while enemy weapons need to be readable but not fatiguing), where you use sidechain ducking versus static compression (specifically: what ducks what, with what parameters), what your loudness budget is per bus so they sum to -16 LUFS on master without the limiter engaging during combat (show the approximate per-bus targets in LUFS), and how you verify the dynamic range is comfortable for headphone players -- what specific test you run and what measurement tells you the fatigue problem is resolved (hint: short-term loudness variance over a 3-minute team fight sample).`
  },
  {
    // 6cc7eae7 - score 6, "no event frequency, memory budget, or fatigue target"
    prefix: '6cc7eae7',
    text: `You are responsible for audio variation on a multiplayer game where the average player session is 4 hours and the game has a 2-year live-service roadmap. A single character's primary attack fires every 0.8 seconds, meaning a player hears it approximately 4,500 times per session. Your memory budget per character soundbank is 16MB, and each uncompressed WAV variant at the required quality (48kHz 16-bit stereo) is approximately 200KB. The character has 45 other events also needing variation, and the total uncompressed size of this character's audio is currently 14.2MB leaving only 1.8MB of headroom. The current implementation uses 4 round-robin variants for the primary attack and playtesters report fatigue at 45 minutes. Your target: no perceptible repetition fatigue at 2 hours. Walk through your methodology: how many base WAV variants you create for this specific event and why (what is the minimum where random-no-repeat becomes perceptually distinct from round-robin at 4,500 repetitions), what real-time parameter randomisation you layer on top (specify the parameter, range, and distribution -- e.g., pitch: +/- 30 cents uniform, filter cutoff: 2kHz-8kHz logarithmic, volume: +/- 1.5dB), what the memory cost of your solution is (variants x size + any additional overhead), how you verify the fatigue target is met (what listening test protocol -- duration, headphone type, number of testers, what question you ask them), and at what point adding more variants has diminishing returns versus investing in parametric randomisation -- show the perceptual inflection point with your reasoning.`
  },
  {
    // ac2a9458 - score 6, "presented as list of examples, not constrained scenario"
    prefix: 'ac2a9458',
    text: `You are setting up RTPCs (Real-Time Parameter Controls) in Wwise for a multiplayer PvE shooter where 4 players fight waves of enemies with increasing intensity. You need to link audio behaviour to three specific gameplay states, each with a different implementation challenge. RTPC 1 -- Health-to-heartbeat: when a player drops below 30% health, a heartbeat sound intensifies. The heartbeat must be audible over combat audio without masking enemy audio tells. The challenge: the heartbeat's low-frequency content (60-100Hz) conflicts with explosion impacts on the same frequency range, and during a boss fight where the player is low health AND explosions are constant, the heartbeat disappears into the mix. What RTPC curve shape do you use (linear, logarithmic, S-curve), what frequency do you EQ the heartbeat to avoid the explosion conflict, and do you duck explosions when the heartbeat is active or find headroom another way? RTPC 2 -- Distance-to-reverb: as the player moves from outdoor (dry) to indoor (reverberant) spaces, reverb sends increase. The challenge: the distance RTPC drives a single reverb aux bus, but the game has 3 acoustically different indoor spaces (stone cathedral, metal warehouse, wooden cabin) that need different reverb characters. How do you handle multiple reverb presets with a single distance RTPC, or do you use a second RTPC (room type) to select the reverb preset? RTPC 3 -- Combat escalation driving music intensity: as the number of enemies within 30 metres increases from 0 to 20, the music adds layers. The challenge: enemies spawn and die rapidly, causing the enemy count to fluctuate between 8 and 15 multiple times per second, which makes the music stutter. What smoothing or hysteresis do you apply to the RTPC value, and how do you prevent the music from oscillating between two intensity states? For each RTPC, describe the Wwise implementation: what game parameter drives it, what curve shape, what the min/max values are, and what it controls on the audio side.`
  },
  {
    // baab8eb9 - score 5, "no platform, UI flow, repetition rate, loudness target, or accessibility constraint"
    prefix: 'baab8eb9',
    text: `You are designing UI audio for a competitive multiplayer game that ships on PC, PS5, and mobile (iOS and Android). The game has a main menu with 6 tabs, a 30-second character select with countdown timer, an in-match HUD showing 3 ability cooldowns (4-second to 90-second durations), kill notifications (up to 3 per second during team fights), 4 ping types (danger, location, help, acknowledged), and post-match rank progression. The specific challenge: the 4-second ability cooldown plays a "ready" pip every 4 seconds -- 15 times per minute -- and within 30 minutes of play, playtesters report the pip is annoying. The current pip is a 200ms sine tone at 2kHz with a sharp attack. The kill notification sound plays up to 3 times within one second during team fights; the current notification is a metallic chime at -12 LUFS that creates an unpleasant beating pattern when 3 overlap. The mobile mix is further constrained: phone speakers have limited low-frequency response below 200Hz, meaning any UI sound relying on bass presence for weight will sound thin on mobile. PS5 uses the DualSense haptic feedback for UI confirmation, which you need to coordinate with the audio timing. Walk through: how you redesign the cooldown pip to reduce fatigue at 15 plays per minute (what frequency, duration, envelope shape, and loudness relative to combat audio), how you handle 3 kill notifications within one second (do you queue them, stack them with pitch variation, or replace the oldest with the newest), what specifically changes between the PC and mobile mixes for UI audio (which sounds change frequency content and how), how you test that the 4 ping types are distinguishable by players who cannot see the screen (what blind test protocol), and what your loudness target for the UI bus is relative to the master (-24 LUFS? -20? -- and why that number relative to combat at -14 LUFS).`
  },
  {
    // c0f96587 - score 6, "needs event count, milestone pressure, and specific failure symptoms"
    prefix: 'c0f96587',
    text: `You are in week 2 of a 12-week mentorship. The team's Wwise project has 1,400 events with no naming convention -- some use CamelCase (FireballExplosion), some use underscores (fireball_explosion), some have the character name first (Mage_Fireball) and some have the ability name first (Fireball_Mage). There is no bus hierarchy: all events route to a flat Master > SFX structure. Soundbanks are set to "generate all" so every bank contains every event, and the total loaded audio is 290MB on a 384MB console budget -- meaning you have only 94MB headroom and 3 new characters are planned before ship. The project has 10 characters and 5 maps in active daily development with 800+ Unreal Blueprint references to Wwise events by string name. You cannot rebuild this project in 12 weeks because structural changes risk breaking Blueprint references. Here is the forced sequencing problem: the naming convention fix is low-risk but high-effort (1,400 events to rename, 800 Blueprint string references to update). The soundbank restructuring is high-impact (could save 150MB by loading per-character instead of everything) but high-risk (changing bank loading requires programmer support, and their sprint is full for 4 weeks). The bus hierarchy is medium-effort, medium-risk (adding sub-buses does not break existing routing, but rerouting 1,400 events takes time). You have one week to show visible progress to the producer. Which do you tackle first and why, what can you achieve in weeks 2-4 without programmer support, what do you defer to weeks 5-12 when the programmer is available, and what documentation do you leave so the migration continues after your mentorship ends -- specifically, what does the migration checklist contain and what automated validation do you create?`
  },
  {
    // cc5d1ed2 - score 6, "lacks concrete timing, voice budget, animation hooks, or combat-density constraints"
    prefix: 'cc5d1ed2',
    text: `You are designing audio for a mage character's primary ability: a channelled beam spell in a 5v5 hero shooter. The wind-up is 0.6 seconds (the character raises their staff and energy gathers at the tip; the animation has a key frame at 0.3s where the staff reaches vertical -- this is where the gameplay designer wants the "charging" sound to peak so enemies hear the audio tell and can dodge). The beam fires continuously for up to 3 seconds, dealing damage every 0.2 seconds (15 damage ticks per beam). The beam can be interrupted by a stun during wind-up, requiring a distinct cancel sound that must play within 1 frame (16.7ms at 60fps) of the stun hitting. During the beam phase, each damage tick on a target produces a per-tick impact sound on the target's position. In a team fight, 3 players could fire this ability simultaneously within audible range, producing up to 45 impact ticks per second across 3 beams plus 3 beam loop instances plus other combat audio. The character's voice budget is 24 simultaneous voices. Walk through your layering: what elements compose the wind-up (and at what frame the energy-gathering sound peaks relative to the 0.3s animation key), what the beam loop consists of (how many layers, what frequency ranges, what makes the loop feel continuous rather than obviously repeating -- specify the loop length), how the beam loop transitions to the cancel sound on a 16.7ms deadline (what Wwise event structure handles instant interruption -- play/stop or switch?), how you keep per-tick impacts readable at 15 hits per second without consuming the voice budget (what voice limit per beam's impacts, what the impact duration must be to avoid overlapping tails), and what priority rules ensure the player's own beam always plays while 2 teammate beams are reduced -- what Wwise priority values and what voice-stealing behaviour.`
  },
  {
    // d32b07f0 - score 4, "no loudness target, platform playback context, monitoring setup, or mastering failure"
    prefix: 'd32b07f0',
    text: `The team has never done a mastering pass on their game audio. You have measured three specific problems using a loudness meter on the master bus while playing on a PS5 devkit through studio monitors: (1) the game's overall loudness is -12 LUFS integrated, which is 4-6 LU louder than comparable titles (Call of Duty sits at -16 to -18 LUFS, Apex Legends at -16 LUFS). Players turn their system volume down and then miss gameplay-critical quiet sounds -- footstep detection rate in playtests drops from 85% to 40% when system volume is lowered to compensate. (2) Cinematics are mixed at -16 LUFS but gameplay is at -12 LUFS, creating a 4 LU jump that causes players to push volume up during cutscenes then get blasted when gameplay resumes -- the community subreddit has 15 posts about this. (3) Low-frequency content below 80Hz is not managed: the sub bass from explosions and the tank character's footsteps is at -6 dBFS peak, causing audible distortion on TV soundbars (60% of the PS5 audience based on Sony's published audio playback data) and bass rumble on laptop speakers that masks mid-range dialogue. The team monitors on near-field studio monitors in a treated room and cannot hear problems 1 or 3 because their monitoring environment is too good. Walk through: what monitoring setup change you make in the studio (add a consumer TV speaker, gaming headset, and laptop as reference -- and which you use for which check), what metering tools you introduce and where in the signal chain (loudness meter after master bus, true-peak meter, spectrum analyser -- and what platform standard you reference for the loudness target: EBU R128 at -23 LUFS or the game industry convention of -16 LUFS, and why you choose what you choose), what mastering chain you build on the master bus (high-pass filter at what frequency, multiband compressor with what crossover points and what per-band settings, limiter at what ceiling), and what 3 specific verification checks the team runs on consumer hardware before each milestone build -- with pass/fail thresholds for each (e.g., "play a team fight scene through TV speakers; if dialogue is inaudible, fail").`
  },
  {
    // d6e0087a - score 4, "too generic, lacks player count, profiler data, or bus symptoms"
    prefix: 'd6e0087a',
    text: `The team's mix collapses during 15v15 large-scale PvP battles on a medieval warfare game built in Unreal with FMOD. The FMOD profiler data shows: voice count peaks at 380 (budget: 256), CPU on the audio thread hits 8ms (budget: 4ms, meaning the audio is dropping frames and causing pops), the master bus is limited at -6 LUFS constantly during fights (target: -16 LUFS), and spatial positioning is completely lost because the voice-stealing system uses a simple "quietest voice dies" algorithm with no priority logic -- so a distant catapult impact at -30dB steals a voice from a nearby sword clash at -40dB (the threshold is absolute volume, not perceptual importance). The Audio Lead built the current bus hierarchy 12 months ago: Master > Music, Master > SFX, Master > Dialogue, with all combat sounds on SFX. They have never used voice priority, virtual voices, or per-bus voice limits. The SFX bus currently has 320 of the 380 active voices during peak combat. Rather than rebuilding it yourself, walk the team through the diagnosis: what FMOD profiler view you open first (Voices? CPU? Levels?) and what specific number you point to as the root cause (hint: it is the voice count, not the CPU -- the CPU is a symptom of too many voices), how you explain why a flat SFX bus works at 5v5 (~40 voices) but fails at 15v15 (~320 voices) using a whiteboard-friendly analogy the whole team can understand, what sub-bus structure you guide them to create (specify: Player_Melee, Player_Ranged, Team_Melee, Team_Ranged, Enemy_Melee, Enemy_Ranged, Footsteps, Impacts, Environment -- with voice limits and priority for each), how virtual voice behaviour should work (at what dB threshold a voice goes virtual, whether it resumes when volume increases or restarts), and what the mix should sound like when working at 15v15 -- list the 4 sounds a player must always hear (their own weapon, the nearest enemy's weapon, footsteps within 5m, and teammate callouts) and the 3 sounds acceptable to lose (distant combat, environmental ambience, teammate weapon impacts beyond 10m).`
  },
];

(async () => {
  let applied = 0;
  for (const r of REWRITES) {
    const result = await pool.query(
      "UPDATE interview_question_bank SET question_text = $1, updated_at = NOW() WHERE id::text LIKE $2 RETURNING id",
      [r.text, r.prefix + '%']
    );
    if (result.rows.length) {
      console.log('APPLIED:', result.rows[0].id);
      applied++;
    } else {
      console.log('NOT FOUND:', r.prefix);
    }
  }
  console.log('\nTotal applied:', applied, 'of', REWRITES.length);
  await pool.end();
})();
