    # Miro board stories (from org_chart summaries + screenshot extraction)
    # All hours at 7h/day
    H = 7.0
    MIRO_STORIES = [
        # ================================================================
        # EPIC 1: PLAYER BUILD
        # ================================================================
        # -- Coloured Faction NPCs --
        ('Faction: Icons', 'Enemies Art', 'Art', 'Concept Art', round(5/H,1), round(10/H,1)),
        ('Faction: Icons', 'Enemies Art', 'Art', 'UX/UI', round(2/H,1), round(4/H,1)),
        ('Faction: Insignias', 'Enemies Art', 'Art', 'Concept Art', round(8/H,1), round(16/H,1)),
        ('Faction: Insignias', 'Enemies Art', 'Art', 'Character Art', round(12/H,1), round(25/H,1)),
        ('Faction: Insignias', 'Enemies Art', 'Art', 'UX/UI', round(3/H,1), round(8/H,1)),
        ('Faction: Insignias', 'Enemies Art', 'Art', 'TechArt', round(8/H,1), round(16/H,1)),
        ('Faction: Banners', 'Enemies Art', 'Art', 'Concept Art', round(10/H,1), round(18/H,1)),
        ('Faction: Banners', 'Enemies Art', 'Art', 'Character Art', round(8/H,1), round(16/H,1)),
        ('Faction: Banners', 'Enemies Art', 'Art', 'TechArt', round(8/H,1), round(16/H,1)),
        ('Faction: Clothing Variations', 'Character Creation & Customization', 'Art', 'Concept Art', round(10/H,1), round(18/H,1)),
        ('Faction: Clothing Variations', 'Character Creation & Customization', 'Art', 'Character Art', round(12/H,1), round(24/H,1)),
        ('Faction: Clothing Variations', 'Character Creation & Customization', 'Art', 'TechArt', round(10/H,1), round(24/H,1)),
        # -- Garment System --
        ('Garment System Options', 'Garment System', 'Art', 'Concept Art', round(20/H,1), round(28/H,1)),
        ('Garment System Options', 'Garment System', 'Art', 'UX/UI', round(40/H,1), round(60/H,1)),
        ('Garment Sets', 'Garment System', 'Art', 'Concept Art', round(12/H,1), round(24/H,1)),
        ('Garment Sets', 'Garment System', 'Art', 'Character Art', round(12/H,1), round(60/H,1)),
        ('Garment Sets', 'Garment System', 'Art', 'TechArt', round(16/H,1), round(24/H,1)),
        ('Armour Sets', 'Garment System', 'Art', 'Concept Art', round(12/H,1), round(24/H,1)),
        ('Armour Sets', 'Garment System', 'Art', 'Character Art', round(12/H,1), round(48/H,1)),
        ('Armour Sets', 'Garment System', 'Art', 'TechArt', round(16/H,1), round(24/H,1)),
        ('Weapon Sets', 'Garment System', 'Art', 'Concept Art', round(24/H,1), round(40/H,1)),
        ('Weapon Sets', 'Garment System', 'Art', 'Character Art', round(16/H,1), round(24/H,1)),
        ('Weapon Sets', 'Garment System', 'Art', 'TechArt', round(16/H,1), round(24/H,1)),
        ('Skins', 'Garment System', 'Art', 'Concept Art', round(24/H,1), round(40/H,1)),
        ('Skins', 'Garment System', 'Art', 'Character Art', round(32/H,1), round(60/H,1)),
        ('Skins', 'Garment System', 'Art', 'TechArt', round(16/H,1), round(24/H,1)),
        ('Partner Skins', 'Garment System', 'Art', 'Concept Art', round(24/H,1), round(64/H,1)),
        ('Partner Skins', 'Garment System', 'Art', 'Character Art', round(8/H,1), round(60/H,1)),
        ('Partner Skins', 'Garment System', 'Art', 'TechArt', round(16/H,1), round(24/H,1)),
        # -- Forge System --
        ('Weapon Parts', 'Professions', 'Art', 'Concept Art', round(4/H,1), round(8/H,1)),
        ('Weapon Parts', 'Professions', 'Art', 'Character Art', round(24/H,1), round(32/H,1)),
        ('Weapon Parts', 'Professions', 'Art', 'VFX', round(24/H,1), round(32/H,1)),
        ('Weapon Parts', 'Professions', 'Art', 'UX/UI', round(40/H,1), round(80/H,1)),
        ('Weapon Parts', 'Professions', 'Art', 'TechArt', round(16/H,1), round(24/H,1)),
        # -- Character Creation & Customisation --
        ('Base Body (MVP DONE)', 'Character Creation & Customization', 'Art', 'Character Art', None, None),
        ('Base Faces (MVP DONE)', 'Character Creation & Customization', 'Art', 'Character Art', None, None),
        ('Char Creation System', 'Character Creation & Customization', 'Art', 'Concept Art', round(12/H,1), round(16/H,1)),
        ('Char Creation System', 'Character Creation & Customization', 'Art', 'UX/UI', round(80/H,1), round(120/H,1)),
        ('Ethnicity Variants', 'Character Creation & Customization', 'Art', 'Concept Art', round(16/H,1), round(24/H,1)),
        ('Ethnicity Variants', 'Character Creation & Customization', 'Art', 'Character Art', round(32/H,1), round(50/H,1)),
        ('Ethnicity Variants', 'Character Creation & Customization', 'Art', 'TechArt', round(16/H,1), round(24/H,1)),
        ('Fantasy Races', 'Character Creation & Customization', 'Art', 'Concept Art', round(24/H,1), round(48/H,1)),
        ('Fantasy Races', 'Character Creation & Customization', 'Art', 'Character Art', round(56/H,1), round(96/H,1)),
        ('Fantasy Races', 'Character Creation & Customization', 'Art', 'TechArt', round(16/H,1), round(24/H,1)),
        ('Race Variants', 'Character Creation & Customization', 'Art', 'Character Art', None, None),
        # -- Professions --
        ('Fishing', 'Professions', 'Art', 'Concept Art', round(24/H,1), round(40/H,1)),
        ('Fishing', 'Professions', 'Art', 'Character Art', round(26/H,1), round(44/H,1)),
        ('Fishing', 'Professions', 'Art', 'Animation & Rigging', round(40/H,1), round(80/H,1)),
        ('Fishing', 'Professions', 'Art', 'UX/UI', round(3/H,1), round(6/H,1)),
        ('Gathering', 'Professions', 'Art', 'Concept Art', round(24/H,1), round(40/H,1)),
        ('Gathering', 'Professions', 'Art', 'Animation & Rigging', round(40/H,1), round(80/H,1)),
        ('Gathering', 'Professions', 'Art', 'UX/UI', round(3/H,1), round(6/H,1)),
        ('Crafting', 'Professions', 'Art', 'Concept Art', round(32/H,1), round(64/H,1)),
        ('Crafting', 'Professions', 'Art', 'Animation & Rigging', round(40/H,1), round(80/H,1)),
        ('Crafting', 'Professions', 'Art', 'UX/UI', round(40/H,1), round(60/H,1)),
        ('Forge Crafting Station', 'Professions', 'Art', 'Concept Art', round(16/H,1), round(32/H,1)),
        ('Forge Crafting Station', 'Professions', 'Art', 'Environment Art', round(40/H,1), round(65/H,1)),
        # -- Achievements & Trophies --
        ('Trophies', 'Achievements & Trophies', 'Art', 'Concept Art', round(10/H,1), round(32/H,1)),
        ('Trophies', 'Achievements & Trophies', 'Art', 'Environment Art', round(24/H,1), round(50/H,1)),
        ('Trophies', 'Achievements & Trophies', 'Art', 'VFX', round(12/H,1), round(40/H,1)),
        ('Trophies', 'Achievements & Trophies', 'Art', 'UX/UI', round(3/H,1), round(4/H,1)),
        ('Text Pop Up', 'Achievements & Trophies', 'Art', 'Concept Art', round(16/H,1), round(32/H,1)),
        ('Text Pop Up', 'Achievements & Trophies', 'Art', 'VFX', round(32/H,1), round(48/H,1)),
        ('Text Pop Up', 'Achievements & Trophies', 'Art', 'UX/UI', round(3/H,1), round(4/H,1)),
        # -- Player Progression --
        ('Player Level Up UI', 'Player Progression', 'Art', 'UX/UI', round(2/H,1), round(4/H,1)),
        ('Character Stats UI', 'Player Progression', 'Art', 'UX/UI', round(2/H,1), round(4/H,1)),
        ('Skill System UI', 'Skill System', 'Art', 'UX/UI', round(2/H,1), round(4/H,1)),
        # ================================================================
        # EPIC 2: WORLD SYSTEMS - ENV
        # ================================================================
        # -- Fluid Ninja Tech R&D --
        ('Lighting Tech', 'Navigation', 'Art', 'TechArt', round(40/H,1), round(56/H,1)),
        ('Atmospherics', 'Navigation', 'Art', 'TechArt', round(40/H,1), round(56/H,1)),
        ('Fog', 'Navigation', 'Art', 'TechArt', round(40/H,1), round(56/H,1)),
        ('Ocean', 'Navigation', 'Art', 'TechArt', round(40/H,1), round(56/H,1)),
        ('River', 'Navigation', 'Art', 'TechArt', round(40/H,1), round(56/H,1)),
        ('Water', 'Navigation', 'Art', 'TechArt', round(40/H,1), round(56/H,1)),
        ('VFX Tech', 'Foam Corruption', 'Art', 'TechArt', round(40/H,1), round(60/H,1)),
        ('VFX Tech', 'Foam Corruption', 'Art', 'VFX', round(40/H,1), round(60/H,1)),
        # -- Zone POIs: FTUE Cave --
        ('POI - Cave', 'FTUE', 'Art', 'Environment Art', None, None),
        ('POI - Tower Exterior', 'FTUE', 'Art', 'Environment Art', None, None),
        ('POI - The Big Battle Hill', 'FTUE', 'Art', 'Environment Art', None, None),
        ('POI - Cave Interior', 'FTUE', 'Art', 'Environment Art', None, None),
        # -- Zone POIs: New TBNL --
        ('POI - Waterfall Beauty', 'Biome - Whispering Woods', 'Art', 'Environment Art', None, None),
        ('POI - Rope Bridge', 'Biome - Portal Peak', 'Art', 'Environment Art', None, None),
        ('POI - Drifters Cross (TBNL)', 'Biome - Portal Peak', 'Art', 'Environment Art', None, None),
        # -- Zone POIs: Downtime (10 POIs) --
        ('POI - Barracks', 'Biome - Downtime', 'Art', 'Environment Art', None, None),
        ('POI - Harbor', 'Biome - Downtime', 'Art', 'Environment Art', None, None),
        ('POI - House of Houses', 'Biome - Downtime', 'Art', 'Environment Art', None, None),
        ('POI - Marketplace', 'Biome - Downtime', 'Art', 'Environment Art', None, None),
        ('POI - Elevator Interior', 'Biome - Downtime', 'Art', 'Environment Art', None, None),
        ('POI - Elevator Top', 'Biome - Downtime', 'Art', 'Environment Art', None, None),
        ('POI - Tranquil Pond', 'Biome - Downtime', 'Art', 'Environment Art', None, None),
        ('POI - Lighthouse', 'Biome - Downtime', 'Art', 'Environment Art', None, None),
        ('POI - Housing District', 'Biome - Downtime', 'Art', 'Environment Art', None, None),
        ('POI - Marketplace 2', 'Biome - Downtime', 'Art', 'Environment Art', None, None),
        # -- Downtime Hero Buildings --
        ('Arcade Facade', 'Biome - Downtime', 'Art', 'Environment Art', round(40/H,1), round(80/H,1)),
        ('Bank Facade', 'Biome - Downtime', 'Art', 'Environment Art', round(65/H,1), round(120/H,1)),
        ('Tavern with Interior', 'Biome - Downtime', 'Art', 'Environment Art', round(80/H,1), round(120/H,1)),
        ('Barber Facade', 'Biome - Downtime', 'Art', 'Environment Art', round(40/H,1), round(80/H,1)),
        # -- Biomes --
        ('Mediterranean Biome', 'Biome - Portal Peak', 'Art', 'Environment Art', None, None),
        ('Cliff - Mediterranean', 'Biome - Portal Peak', 'Art', 'Environment Art', None, None),
        ('Lush Biome', 'Biome - Farmlands', 'Art', 'Environment Art', None, None),
        # -- Navigation --
        ('Compass/Mini Map', 'Navigation', 'Art', 'UX/UI', round(4/H,1), round(10/H,1)),
        ('Compass/Mini Map', 'Navigation', 'Art', 'Concept Art', round(24/H,1), round(64/H,1)),
        ('Markers', 'Navigation', 'Art', 'Concept Art', round(16/H,1), round(40/H,1)),
        ('Markers', 'Navigation', 'Art', 'VFX', round(24/H,1), round(32/H,1)),
        ('Markers', 'Navigation', 'Art', 'UX/UI', round(4/H,1), round(10/H,1)),
        ('Maps', 'Navigation', 'Art', 'Concept Art', round(40/H,1), round(80/H,1)),
        ('Maps', 'Navigation', 'Art', 'VFX', round(24/H,1), round(32/H,1)),
        ('Maps', 'Navigation', 'Art', 'UX/UI', round(20/H,1), round(40/H,1)),
        ('Maps - Env Blockout', 'Navigation', 'Art', 'Environment Art', round(500/H,1), round(720/H,1)),
        # -- Partner Portal --
        ('Partner Portal (placeholder)', 'Partner Portal', 'Art', 'UX/UI', round(4/H,1), round(12/H,1)),
        ('Partner Portal (placeholder)', 'Partner Portal', 'Art', 'Concept Art', round(40/H,1), round(80/H,1)),
        ('Partner Portal (placeholder)', 'Partner Portal', 'Art', 'VFX', round(40/H,1), round(64/H,1)),
        ('Partner Portal (placeholder)', 'Partner Portal', 'Art', 'Environment Art', round(80/H,1), round(100/H,1)),
        # -- Env Architecture Kits (proxy+final combined) --
        ('Env Arch Kit - Mythcore', 'Biome - Portal Peak', 'Art', 'Environment Art', round(80/H,1), round(140/H,1)),
        ('Env Arch Kit - Graveyard', 'Biome - Portal Peak', 'Art', 'Environment Art', round(80/H,1), round(220/H,1)),
        ('Env Arch Kit - Mythcore Ruin', 'Biome - Portal Peak', 'Art', 'Environment Art', round(80/H,1), round(140/H,1)),
        ('Env Arch Kit - Fantasy', 'Biome - Portal Peak', 'Art', 'Environment Art', round(80/H,1), round(460/H,1)),
        ('Env Arch Kit - Guild Hall', 'Guilds', 'Art', 'Environment Art', round(120/H,1), round(545/H,1)),
        ('Env Arch Kit - Player Housing', 'Building Houses', 'Art', 'Environment Art', round(200/H,1), round(690/H,1)),
        ('Env Arch Kit - Arena', 'PvP Combat', 'Art', 'Environment Art', round(120/H,1), round(540/H,1)),
        ('Env Arch Kit - Deck/Scaffolding', 'Biome - Portal Peak', 'Art', 'Environment Art', round(80/H,1), round(230/H,1)),
        ('Env Arch Kit - Wooden Camp', 'Biome - Portal Peak', 'Art', 'Environment Art', round(120/H,1), round(300/H,1)),
        # -- Env Prop Kits (concept+proxy+final combined) --
        ('Env Prop Kit - Mythcore', 'Biome - Portal Peak', 'Art', 'Environment Art', round(140/H,1), round(225/H,1)),
        ('Env Prop Kit - Graveyard', 'Biome - Portal Peak', 'Art', 'Environment Art', round(160/H,1), round(315/H,1)),
        ('Env Prop Kit - Mythcore Ruin', 'Biome - Portal Peak', 'Art', 'Environment Art', round(140/H,1), round(235/H,1)),
        ('Env Prop Kit - Fantasy', 'Biome - Portal Peak', 'Art', 'Environment Art', round(200/H,1), round(985/H,1)),
        ('Env Prop Kit - Arena', 'PvP Combat', 'Art', 'Environment Art', round(120/H,1), round(1055/H,1)),
        ('Env Prop Kit - Deck/Scaffolding', 'Biome - Portal Peak', 'Art', 'Environment Art', round(120/H,1), round(915/H,1)),
        ('Env Prop Kit - Wooden Camp', 'Biome - Portal Peak', 'Art', 'Environment Art', round(200/H,1), round(315/H,1)),
        ('Env Prop Kit - Tavern', 'Biome - Downtime', 'Art', 'Environment Art', round(120/H,1), round(355/H,1)),
        # -- Env Furniture Kits (concept+proxy+final combined) --
        ('Env Furniture Kit - Fantasy', 'User Space Decoration', 'Art', 'Environment Art', round(430/H,1), round(630/H,1)),
        ('Env Furniture Kit - Graveyard', 'Biome - Portal Peak', 'Art', 'Environment Art', round(500/H,1), round(610/H,1)),
        ('Env Furniture Kit - Gritcore', 'User Space Decoration', 'Art', 'Environment Art', round(450/H,1), round(670/H,1)),
        ('Env Furniture Kit - Mythcore', 'Biome - Portal Peak', 'Art', 'Environment Art', round(460/H,1), round(620/H,1)),
        ('Env Furniture Kit - Bug Dungeon', 'Dungeon Mechanics', 'Art', 'Environment Art', round(510/H,1), round(630/H,1)),
        # -- Corruption --
        ('Corruption: Vines', 'Foam Corruption', 'Art', 'Concept Art', round(50/H,1), round(60/H,1)),
        ('Corruption: Vines', 'Foam Corruption', 'Art', 'TechArt', round(80/H,1), round(120/H,1)),
        ('Corruption: Vines', 'Foam Corruption', 'Art', 'UX/UI', round(4/H,1), round(10/H,1)),
        ('Corruption: Vines', 'Foam Corruption', 'Art', 'Environment Art', round(40/H,1), round(60/H,1)),
        ('Corruption: Foam', 'Foam Corruption', 'Art', 'Concept Art', round(40/H,1), round(64/H,1)),
        ('Corruption: Foam', 'Foam Corruption', 'Art', 'VFX', round(40/H,1), round(64/H,1)),
        ('Corruption: Foam', 'Foam Corruption', 'Art', 'Environment Art', round(60/H,1), round(80/H,1)),
        ('Corruption: Time', 'Time Corruption', 'Art', 'Concept Art', round(40/H,1), round(64/H,1)),
        ('Corruption: Time', 'Time Corruption', 'Art', 'UX/UI', round(4/H,1), round(10/H,1)),
        ('Corruption: Time', 'Time Corruption', 'Art', 'VFX', round(40/H,1), round(64/H,1)),
        ('Corruption: Time', 'Time Corruption', 'Art', 'TechArt', round(80/H,1), round(120/H,1)),
        ('Corruption: Time', 'Time Corruption', 'Art', 'Environment Art', round(120/H,1), round(160/H,1)),
        # ================================================================
        # EPIC 3: WORLD SYSTEMS - THE REST
        # ================================================================
        # -- Critter NPCs --
        ('Cows', 'Enemies Art', 'Art', 'Concept Art', round(14/H,1), round(32/H,1)),
        ('Cows', 'Enemies Art', 'Art', 'Character Art', round(32/H,1), round(60/H,1)),
        ('Cows', 'Enemies Art', 'Art', 'Animation & Rigging', round(112/H,1), round(205/H,1)),
        ('Chickens', 'Enemies Art', 'Art', 'Concept Art', round(14/H,1), round(32/H,1)),
        ('Chickens', 'Enemies Art', 'Art', 'Character Art', round(16/H,1), round(24/H,1)),
        ('Chickens', 'Enemies Art', 'Art', 'Animation & Rigging', round(38/H,1), round(62/H,1)),
        ('Horses', 'Enemies Art', 'Art', 'Concept Art', round(24/H,1), round(32/H,1)),
        ('Horses', 'Enemies Art', 'Art', 'Character Art', round(32/H,1), round(66/H,1)),
        ('Horses', 'Enemies Art', 'Art', 'Animation & Rigging', round(40/H,1), round(60/H,1)),
        ('Pigs', 'Enemies Art', 'Art', 'Concept Art', round(24/H,1), round(40/H,1)),
        ('Pigs', 'Enemies Art', 'Art', 'Character Art', round(24/H,1), round(32/H,1)),
        ('Pigs', 'Enemies Art', 'Art', 'Animation & Rigging', round(112/H,1), round(145/H,1)),
        ('Hares', 'Enemies Art', 'Art', 'Concept Art', round(16/H,1), round(32/H,1)),
        ('Hares', 'Enemies Art', 'Art', 'Character Art', round(16/H,1), round(24/H,1)),
        ('Hares', 'Enemies Art', 'Art', 'Animation & Rigging', round(112/H,1), round(148/H,1)),
        ('Sheep', 'Enemies Art', 'Art', 'Concept Art', round(24/H,1), round(32/H,1)),
        ('Sheep', 'Enemies Art', 'Art', 'Character Art', round(24/H,1), round(30/H,1)),
        ('Sheep', 'Enemies Art', 'Art', 'Animation & Rigging', round(112/H,1), round(148/H,1)),
        # -- Hero NPCs --
        ('Hero NPC - Xyron (Upgrade)', 'Enemies Art', 'Art', 'Concept Art', round(40/H,1), round(64/H,1)),
        ('Hero NPC - Xyron (Upgrade)', 'Enemies Art', 'Art', 'Character Art', round(32/H,1), round(48/H,1)),
        ('Hero NPC - Xyron (Upgrade)', 'Enemies Art', 'Art', 'Animation & Rigging', round(34/H,1), round(70/H,1)),
        ('Hero NPC - Green Faction', 'Enemies Art', 'Art', 'Concept Art', round(40/H,1), round(80/H,1)),
        ('Hero NPC - Green Faction', 'Enemies Art', 'Art', 'Character Art', round(32/H,1), round(48/H,1)),
        ('Hero NPC - Green Faction', 'Enemies Art', 'Art', 'Animation & Rigging', round(34/H,1), round(70/H,1)),
        ('Hero NPC - Barbersmith (Upgrade)', 'Enemies Art', 'Art', 'Character Art', None, None),
        ('Hero NPC - Maeve/Mayor (Upgrade)', 'Enemies Art', 'Art', 'Character Art', None, None),
        # -- Human NPCs --
        ('Green Faction NPCs', 'Enemies Art', 'Art', 'Concept Art', round(23/H,1), round(64/H,1)),
        ('Green Faction NPCs', 'Enemies Art', 'Art', 'Character Art', round(23/H,1), round(36/H,1)),
        ('Green Faction NPCs', 'Enemies Art', 'Art', 'Animation & Rigging', round(31/H,1), round(57/H,1)),
        ('Green Faction NPCs', 'Enemies Art', 'Art', 'TechArt', round(8/H,1), round(16/H,1)),
        ('Blue Faction NPCs', 'Enemies Art', 'Art', 'Concept Art', round(32/H,1), round(64/H,1)),
        ('Blue Faction NPCs', 'Enemies Art', 'Art', 'Character Art', round(32/H,1), round(50/H,1)),
        ('Blue Faction NPCs', 'Enemies Art', 'Art', 'Animation & Rigging', round(12/H,1), round(30/H,1)),
        ('Blue Faction NPCs', 'Enemies Art', 'Art', 'TechArt', round(8/H,1), round(16/H,1)),
        ('Red Faction NPCs', 'Enemies Art', 'Art', 'Concept Art', round(32/H,1), round(64/H,1)),
        ('Red Faction NPCs', 'Enemies Art', 'Art', 'Character Art', round(32/H,1), round(50/H,1)),
        ('Red Faction NPCs', 'Enemies Art', 'Art', 'Animation & Rigging', round(10/H,1), round(30/H,1)),
        ('Red Faction NPCs', 'Enemies Art', 'Art', 'TechArt', round(8/H,1), round(16/H,1)),
        ('Yellow Faction NPCs', 'Enemies Art', 'Art', 'Concept Art', round(32/H,1), round(64/H,1)),
        ('Yellow Faction NPCs', 'Enemies Art', 'Art', 'Character Art', round(10/H,1), round(32/H,1)),
        ('Yellow Faction NPCs', 'Enemies Art', 'Art', 'Animation & Rigging', round(10/H,1), round(32/H,1)),
        ('Yellow Faction NPCs', 'Enemies Art', 'Art', 'TechArt', round(8/H,1), round(16/H,1)),
        ('Generic NPC', 'Enemies Art', 'Art', 'Concept Art', round(16/H,1), round(20/H,1)),
        ('Generic NPC', 'Enemies Art', 'Art', 'Character Art', round(27/H,1), round(56/H,1)),
        ('Generic NPC', 'Enemies Art', 'Art', 'Animation & Rigging', round(34/H,1), round(80/H,1)),
        ('Generic NPC', 'Enemies Art', 'Art', 'TechArt', round(8/H,1), round(16/H,1)),
        # -- Player Mechanics --
        ('Locomotion', 'Basic Movement System', 'Art', 'VFX', round(40/H,1), round(64/H,1)),
        ('Locomotion', 'Basic Movement System', 'Art', 'Animation & Rigging', round(16/H,1), round(32/H,1)),
        ('Player Environment', 'Basic Movement System', 'Art', 'Animation & Rigging', round(12/H,1), round(40/H,1)),
        ('Gliding', 'Advanced Traversal', 'Art', 'Concept Art', round(20/H,1), round(30/H,1)),
        ('Gliding', 'Advanced Traversal', 'Art', 'VFX', round(16/H,1), round(80/H,1)),
        ('Gliding', 'Advanced Traversal', 'Art', 'Animation & Rigging', round(16/H,1), round(32/H,1)),
        ('Grappling', 'Advanced Traversal', 'Art', 'Concept Art', round(20/H,1), round(38/H,1)),
        ('Grappling', 'Advanced Traversal', 'Art', 'VFX', round(16/H,1), round(40/H,1)),
        ('Grappling', 'Advanced Traversal', 'Art', 'Animation & Rigging', round(10/H,1), round(24/H,1)),
        # -- Cinematics --
        ('Static Pictures Intro + Voiceover', 'Full Motion Video (FMV)', 'Art', 'Concept Art', round(160/H,1), round(200/H,1)),
        ('Static Pictures Intro + Voiceover', 'Full Motion Video (FMV)', 'Art', 'VFX', round(8/H,1), round(17/H,1)),
        ('FMV/Pre-Rendered Cinematics', 'Full Motion Video (FMV)', 'Art', 'Concept Art', round(60/H,1), round(120/H,1)),
        ('2.5D Cinematics', 'In Game Cinematic (IGC)', 'Art', 'Concept Art', None, None),
        ('IGC (In Game Cinematics)', 'In Game Cinematic (IGC)', 'Art', 'Animation & Rigging', None, None),
        # ================================================================
        # EPIC 4: COMBAT
        # ================================================================
        ('Combat Hit & Dmg', 'Combat Framework', 'Art', 'UX/UI', round(6/H,1), round(12/H,1)),
        ('Combat Hit & Dmg', 'Combat Framework', 'Art', 'Concept Art', round(6/H,1), round(12/H,1)),
        ('Magic', 'Magic', 'Art', 'Animation & Rigging', round(16/H,1), round(24/H,1)),
        ('Magic', 'Magic', 'Art', 'Concept Art', round(6/H,1), round(8/H,1)),
        ('Magic', 'Magic', 'Art', 'VFX', round(40/H,1), round(64/H,1)),
        ('Magic', 'Magic', 'Art', 'UX/UI', round(10/H,1), round(24/H,1)),
        ('Player Combat Abilities', 'Combat Abilities', 'Art', 'Animation & Rigging', round(24/H,1), round(80/H,1)),
        ('Player Combat Abilities', 'Combat Abilities', 'Art', 'UX/UI', round(10/H,1), round(30/H,1)),
        # -- Enemies --
        ('Goblins', 'Enemies Art', 'Art', 'Concept Art', round(6/H,1), round(8/H,1)),
        ('Goblins', 'Enemies Art', 'Art', 'Character Art', round(24/H,1), round(40/H,1)),
        ('Goblins', 'Enemies Art', 'Art', 'Animation & Rigging', round(20/H,1), round(30/H,1)),
        ('Slimes', 'Enemies Art', 'Art', 'Concept Art', round(6/H,1), round(8/H,1)),
        ('Slimes', 'Enemies Art', 'Art', 'Animation & Rigging', round(24/H,1), round(30/H,1)),
        ('Slimes', 'Enemies Art', 'Art', 'VFX', round(16/H,1), round(62/H,1)),
        ('Skeletons', 'Enemies Art', 'Art', 'Concept Art', round(4/H,1), round(12/H,1)),
        ('Skeletons', 'Enemies Art', 'Art', 'Character Art', round(32/H,1), round(48/H,1)),
        ('Skeletons', 'Enemies Art', 'Art', 'Animation & Rigging', round(20/H,1), round(40/H,1)),
        ('Skeletons', 'Enemies Art', 'Art', 'VFX', round(40/H,1), round(64/H,1)),
        ('Wolves', 'Enemies Art', 'Art', 'Concept Art', round(40/H,1), round(72/H,1)),
        ('Wolves', 'Enemies Art', 'Art', 'Character Art', round(32/H,1), round(48/H,1)),
        ('Wolves', 'Enemies Art', 'Art', 'Animation & Rigging', round(36/H,1), round(100/H,1)),
        ('Wolves', 'Enemies Art', 'Art', 'VFX', round(40/H,1), round(64/H,1)),
        ('Carapax Enemy', 'Enemies Art', 'Art', 'Concept Art', round(60/H,1), round(90/H,1)),
        ('Carapax Enemy', 'Enemies Art', 'Art', 'Character Art', round(32/H,1), round(48/H,1)),
        ('Carapax Enemy', 'Enemies Art', 'Art', 'Animation & Rigging', round(36/H,1), round(160/H,1)),
        ('Carapax Enemy', 'Enemies Art', 'Art', 'VFX', round(40/H,1), round(64/H,1)),
        # ================================================================
        # EPIC 5: USER SPACE
        # ================================================================
        ('User Space Interior', 'User Space Decoration', 'Art', 'Concept Art', round(10/H,1), round(30/H,1)),
        ('User Space Interior', 'User Space Decoration', 'Art', 'VFX', round(8/H,1), round(15/H,1)),
        ('User Space Interior', 'User Space Decoration', 'Art', 'UX/UI', round(15/H,1), round(15/H,1)),
        ('User Space Interior - Env Kit', 'User Space Decoration', 'Art', 'Environment Art', round(160/H,1), round(184/H,1)),
        ('Modular Houses Interior', 'Building Houses', 'Art', 'UX/UI', round(12/H,1), round(24/H,1)),
        ('Modular Houses Interior', 'Building Houses', 'Art', 'Environment Art', round(120/H,1), round(1384/H,1)),
        ('Dock - User Space Island', 'User Space Server & Instance', 'Art', 'Environment Art', None, None),
        ('Anywhere Door (placeholder)', 'Anywhere Door Placement', 'Art', 'UX/UI', round(4/H,1), round(8/H,1)),
        ('Anywhere Door (placeholder)', 'Anywhere Door Placement', 'Art', 'Concept Art', round(4/H,1), round(8/H,1)),
        ('Anywhere Door (placeholder)', 'Anywhere Door Placement', 'Art', 'Environment Art', round(60/H,1), round(80/H,1)),
        ('Anywhere Door (placeholder)', 'Anywhere Door Placement', 'Art', 'VFX', round(4/H,1), round(8/H,1)),
        # ================================================================
        # EPIC 6: ITEMS & INVENTORY
        # ================================================================
        ('Potions', 'Consumables', 'Art', 'Concept Art', round(8/H,1), round(16/H,1)),
        ('Potions', 'Consumables', 'Art', 'Character Art', round(1/H,1), round(2/H,1)),
        ('Potions', 'Consumables', 'Art', 'VFX', round(40/H,1), round(56/H,1)),
        ('Potions', 'Consumables', 'Art', 'Animation & Rigging', round(16/H,1), round(24/H,1)),
        ('Potions', 'Consumables', 'Art', 'UX/UI', round(2/H,1), round(6/H,1)),
        ('Item Core System (placeholder)', 'Item Core System', 'Art', 'UX/UI', round(2/H,1), round(4/H,1)),
        ('Equipment System (placeholder)', 'Equipment System', 'Art', 'UX/UI', round(20/H,1), round(40/H,1)),
        ('Equipment System (placeholder)', 'Equipment System', 'Art', 'Concept Art', round(20/H,1), round(30/H,1)),
        ('MECH PARROT', 'Mounts / Pets', 'Art', 'Character Art', round(24/H,1), round(32/H,1)),
        ('MECH PARROT', 'Mounts / Pets', 'Art', 'Animation & Rigging', round(16/H,1), round(56/H,1)),
        ('MECH PARROT', 'Mounts / Pets', 'Art', 'VFX', round(40/H,1), round(56/H,1)),
        ('Loot Distribution (placeholder)', 'Loot Distribution', 'Art', 'UX/UI', round(18/H,1), round(22/H,1)),
        ('Loot Distribution (placeholder)', 'Loot Distribution', 'Art', 'Concept Art', round(12/H,1), round(40/H,1)),
        ('Loot Distribution (placeholder)', 'Loot Distribution', 'Art', 'VFX', round(40/H,1), round(56/H,1)),
        ('Inventory System (placeholder)', 'Inventory System', 'Art', 'UX/UI', round(40/H,1), round(80/H,1)),
        ('Inventory System (placeholder)', 'Inventory System', 'Art', 'Concept Art', round(10/H,1), round(16/H,1)),
        # ================================================================
        # EPIC 7: QUEST SYSTEM
        # ================================================================
        ('Lock Picking Quest', 'Quest Types - Courier / Escort / Kill / Collect / Mystery / Time / Partner / Lockpicking', 'Art', 'Concept Art', round(60/H,1), round(72/H,1)),
        ('Lock Picking Quest', 'Quest Types - Courier / Escort / Kill / Collect / Mystery / Time / Partner / Lockpicking', 'Art', 'UX/UI', round(12/H,1), round(40/H,1)),
        ('Lock Picking Quest', 'Quest Types - Courier / Escort / Kill / Collect / Mystery / Time / Partner / Lockpicking', 'Art', 'TechArt', round(12/H,1), round(48/H,1)),
        ('Lock Picking Quest', 'Quest Types - Courier / Escort / Kill / Collect / Mystery / Time / Partner / Lockpicking', 'Art', 'VFX', round(45/H,1), round(56/H,1)),
        ('Hearthstone (Return Home Stone)', 'Quest Reward System', 'Art', 'Concept Art', round(10/H,1), round(12/H,1)),
        ('Hearthstone (Return Home Stone)', 'Quest Reward System', 'Art', 'Environment Art', round(16/H,1), round(24/H,1)),
        ('Hearthstone (Return Home Stone)', 'Quest Reward System', 'Art', 'VFX', round(60/H,1), round(80/H,1)),
        ('Hearthstone (Return Home Stone)', 'Quest Reward System', 'Art', 'UX/UI', round(6/H,1), round(8/H,1)),
        ('Partner Crystal', 'Quest Reward System', 'Art', 'Concept Art', round(5/H,1), round(12/H,1)),
        ('Partner Crystal', 'Quest Reward System', 'Art', 'Environment Art', round(40/H,1), round(72/H,1)),
        ('Partner Crystal', 'Quest Reward System', 'Art', 'UX/UI', round(10/H,1), round(20/H,1)),
        ('Quest Reward System (placeholder)', 'Quest Reward System', 'Art', 'Concept Art', round(24/H,1), round(32/H,1)),
        ('Quest Reward System (placeholder)', 'Quest Reward System', 'Art', 'UX/UI', round(10/H,1), round(20/H,1)),
        ('Quest Log (placeholder)', 'Quest Log', 'Art', 'Concept Art', round(24/H,1), round(32/H,1)),
        ('Quest Log (placeholder)', 'Quest Log', 'Art', 'UX/UI', round(10/H,1), round(20/H,1)),
        ('Quest Dialog GUI (placeholder)', 'Quest Dialog GUI', 'Art', 'Concept Art', round(10/H,1), round(20/H,1)),
        ('Quest Dialog GUI (placeholder)', 'Quest Dialog GUI', 'Art', 'UX/UI', round(10/H,1), round(20/H,1)),
        ('Quest Narrative (placeholder)', 'Quest Narrative Content', 'Art', 'Concept Art', round(24/H,1), round(24/H,1)),
        ('Quest Narrative (placeholder)', 'Quest Narrative Content', 'Art', 'UX/UI', round(10/H,1), round(20/H,1)),
        ('Quest Multiplayer (placeholder)', 'Quest Multiplayer', 'Art', 'Concept Art', round(24/H,1), round(24/H,1)),
        ('Quest Multiplayer (placeholder)', 'Quest Multiplayer', 'Art', 'UX/UI', round(12/H,1), round(24/H,1)),
        ('Quests Backend (placeholder)', 'Quests Backend / Tooling', 'Art', 'Concept Art', round(24/H,1), round(32/H,1)),
        ('Quests Backend (placeholder)', 'Quests Backend / Tooling', 'Art', 'UX/UI', round(12/H,1), round(24/H,1)),
        # ================================================================
        # EPIC 8: PLAYER ECONOMY
        # ================================================================
        ('Garment Shop (placeholder)', 'In-game Store', 'Art', 'Concept Art', round(40/H,1), round(60/H,1)),
        ('Garment Shop (placeholder)', 'In-game Store', 'Art', 'UX/UI', round(20/H,1), round(30/H,1)),
        ('Trading System (placeholder)', 'Trading System', 'Art', 'Concept Art', round(40/H,1), round(60/H,1)),
        ('Trading System (placeholder)', 'Trading System', 'Art', 'UX/UI', round(10/H,1), round(20/H,1)),
        ('Currency', 'Currency System', 'Art', 'Concept Art', round(5/H,1), round(10/H,1)),
        ('Currency', 'Currency System', 'Art', 'UX/UI', round(10/H,1), round(20/H,1)),
        ('Currency', 'Currency System', 'Art', 'Environment Art', round(8/H,1), round(16/H,1)),
        ('Currency', 'Currency System', 'Art', 'VFX', round(32/H,1), round(40/H,1)),
        ('Bugged Dungeon Shop', 'Dungeon Mechanics', 'Art', 'Concept Art', round(30/H,1), round(40/H,1)),
        ('Bugged Dungeon Shop', 'Dungeon Mechanics', 'Art', 'UX/UI', round(10/H,1), round(20/H,1)),
        ('Bugged Dungeon Shop', 'Dungeon Mechanics', 'Art', 'Environment Art', round(40/H,1), round(120/H,1)),
        ('Bugged Dungeon Shop', 'Dungeon Mechanics', 'Art', 'VFX', round(32/H,1), round(40/H,1)),
        # ================================================================
        # EPIC 9: SOCIAL & MULTIPLAYER
        # ================================================================
        ('In-Game Mail (placeholder)', 'In-game Mail', 'Art', 'Concept Art', round(16/H,1), round(32/H,1)),
        ('In-Game Mail (placeholder)', 'In-game Mail', 'Art', 'UX/UI', round(12/H,1), round(20/H,1)),
        ('Co-Op/Party (placeholder)', 'Co-op / Party', 'Art', 'Concept Art', round(24/H,1), round(40/H,1)),
        ('Co-Op/Party (placeholder)', 'Co-op / Party', 'Art', 'UX/UI', round(10/H,1), round(20/H,1)),
        ('Guild Systems (placeholder)', 'Guilds', 'Art', 'Concept Art', round(24/H,1), round(40/H,1)),
        ('Guild Systems (placeholder)', 'Guilds', 'Art', 'UX/UI', round(10/H,1), round(20/H,1)),
        ('Game Chat System (placeholder)', 'Game Chat System', 'Art', 'Concept Art', round(10/H,1), round(50/H,1)),
        ('Game Chat System (placeholder)', 'Game Chat System', 'Art', 'UX/UI', round(12/H,1), round(24/H,1)),
        # ================================================================
        # EPIC 10: GAME BIBLES
        # ================================================================
        ('Colour Palette', 'UX/UI Bible', 'Art', 'Concept Art', round(40/H,1), round(60/H,1)),
        ('Typography', 'UX/UI Bible', 'Art', 'Concept Art', round(40/H,1), round(60/H,1)),
        ('Wireframes', 'UX/UI Bible', 'Art', 'UX/UI', round(40/H,1), round(60/H,1)),
        ('Game Logo', 'Brand Bible', 'Art', 'Concept Art', round(80/H,1), round(120/H,1)),
        ('ENV Bible', 'Art Bible', 'Art', 'Environment Art', round(80/H,1), round(100/H,1)),
        ('ANIM Bible', 'Art Bible', 'Art', 'Animation & Rigging', round(80/H,1), round(100/H,1)),
        ('CHAR Bible', 'Art Bible', 'Art', 'Character Art', round(80/H,1), round(100/H,1)),
        ('VFX Bible', 'Art Bible', 'Art', 'VFX', round(80/H,1), round(100/H,1)),
        ('CONCEPT Bible', 'Art Bible', 'Art', 'Concept Art', round(80/H,1), round(100/H,1)),
        ('Accessibility Bible', 'Accessibility Guidelines', 'Art', 'UX/UI', None, None),
    ]
